// frontend-vue/src/app/inscription/page.vue
<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { Building2, Mail, Lock, Eye, EyeOff, User, Phone, ArrowRight, CheckCircle2 } from 'lucide-vue-next'
import { registerUser } from '@/lib/api'

const router = useRouter()

// États du formulaire
const showPassword = ref(false)
const showConfirmPassword = ref(false)
const isLoading = ref(false)
const errors = ref({})

const formData = reactive({
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  password: "",
  confirmPassword: "",
  acceptTerms: false,
})

// Logique de validation
const validate = () => {
  const newErrors = {}

  if (!formData.firstName) newErrors.firstName = "Le prénom est requis"
  if (!formData.lastName) newErrors.lastName = "Le nom est requis"
  if (!formData.email) newErrors.email = "L'email est requis"
  if (!formData.password) newErrors.password = "Le mot de passe est requis"
  if (formData.password.length < 8) {
    newErrors.password = "Minimum 8 caractères"
  }
  if (formData.password !== formData.confirmPassword) {
    newErrors.confirmPassword = "Les mots de passe diffèrent"
  }
  if (!formData.acceptTerms) {
    newErrors.acceptTerms = "Obligatoire"
  }

  errors.value = newErrors
  return Object.keys(newErrors).length === 0
}

const handleSubmit = async () => {
  if (!validate()) return

  isLoading.value = true

  try {
    await registerUser({
      name: `${formData.firstName} ${formData.lastName}`.trim(),
      email: formData.email,
      phone: formData.phone,
      password: formData.password,
    })

    router.push('/connexion')
  } catch (err) {
    errors.value = { submit: err instanceof Error ? err.message : "L'inscription a échoué" }
  }

  isLoading.value = false
}
</script>

<template>
  <div class="min-h-screen flex bg-[#f8fafc] font-sans antialiased text-slate-900">
    
    <div class="hidden lg:flex lg:w-1/2 bg-[#0f172a] relative overflow-hidden">
      <div class="absolute -top-24 -right-24 w-96 h-96 bg-[#0070f3] opacity-20 blur-[100px] rounded-full" />
      <div class="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-[#0070f3]/20 to-transparent" />

      <div class="relative z-10 flex flex-col justify-center p-16 w-full">
        <div class="inline-flex p-3 bg-white/10 backdrop-blur-md rounded-2xl mb-8 w-fit border border-white/10">
          <Building2 class="h-10 w-10 text-[#0070f3]" />
        </div>
        
        <h2 class="text-5xl font-extrabold text-white mb-6 leading-tight">
          Rejoignez la <br />
          <span class="text-[#0070f3]">communauté.</span>
        </h2>
        
        <div class="space-y-6 mt-8">
          <div v-for="(text, i) in ['Accès gratuit au catalogue', 'Suivi de vos demandes en direct', 'Support client dédié 7j/7']" :key="i" class="flex items-center gap-4 text-slate-300 text-lg">
            <CheckCircle2 class="h-6 w-6 text-[#0070f3]" />
            <span>{{ text }}</span>
          </div>
        </div>

        <div class="mt-16 p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm max-w-md">
          <p class="text-slate-400 italic">"L'inscription a pris moins de 2 minutes et j'ai pu visiter mon premier appartement le lendemain."</p>
          <div class="mt-4 flex items-center gap-3">
            <div class="w-10 h-10 rounded-full bg-slate-700 flex items-center justify-center text-xs text-white">SC</div>
            <div>
              <p class="text-white font-bold text-sm">Sophie Colin</p>
              <p class="text-slate-500 text-xs">Utilisatrice vérifiée</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="flex-1 flex flex-col justify-center items-center py-12 px-6 lg:px-12 bg-slate-50">
      <div class="w-full max-w-xl">
        
        <div class="bg-white rounded-[2rem] shadow-2xl shadow-slate-200 border border-slate-100 overflow-hidden">
          <div class="p-8 lg:p-10">
            <div class="mb-8 text-center lg:text-left">
              <h1 class="text-2xl font-bold text-[#0f172a]">Créer un compte</h1>
              <p class="text-slate-500 text-sm mt-1">Commencez votre recherche immobilière dès maintenant.</p>
            </div>

            <form @submit.prevent="handleSubmit" class="space-y-4">
              <div v-if="errors.submit" class="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                {{ errors.submit }}
              </div>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div class="space-y-1">
                  <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Prénom</label>
                  <div class="relative group">
                    <User class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 group-focus-within:text-[#0070f3] transition-colors" />
                    <input v-model="formData.firstName" type="text" placeholder="Jean"
                      :class="['w-full pl-12 pr-4 py-3.5 bg-slate-50 border rounded-2xl transition-all outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]', 
                      errors.firstName ? 'border-red-300' : 'border-slate-200']" />
                  </div>
                </div>
                <div class="space-y-1">
                  <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Nom</label>
                  <input v-model="formData.lastName" type="text" placeholder="Dupont"
                    :class="['w-full px-4 py-3.5 bg-slate-50 border rounded-2xl transition-all outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]', 
                    errors.lastName ? 'border-red-300' : 'border-slate-200']" />
                </div>
              </div>

              <div class="space-y-1">
                <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Email professionnel ou perso</label>
                <div class="relative group">
                  <Mail class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 group-focus-within:text-[#0070f3] transition-colors" />
                  <input v-model="formData.email" type="email" placeholder="jean@exemple.com"
                    :class="['w-full pl-12 pr-4 py-3.5 bg-slate-50 border rounded-2xl transition-all outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]', 
                    errors.email ? 'border-red-300' : 'border-slate-200']" />
                </div>
              </div>

              <div class="space-y-1">
                <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Téléphone (Optionnel)</label>
                <div class="relative group">
                  <Phone class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 group-focus-within:text-[#0070f3] transition-colors" />
                  <input v-model="formData.phone" type="tel" placeholder="06 00 00 00 00"
                    class="w-full pl-12 pr-4 py-3.5 bg-slate-50 border border-slate-200 rounded-2xl outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]" />
                </div>
              </div>

              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div class="space-y-1">
                  <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Mot de passe</label>
                  <div class="relative group">
                    <Lock class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400" />
                    <input v-model="formData.password" :type="showPassword ? 'text' : 'password'" placeholder="••••••••"
                      :class="['w-full pl-11 pr-10 py-3.5 bg-slate-50 border rounded-2xl transition-all outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]', 
                      errors.password ? 'border-red-300' : 'border-slate-200']" />
                    <button type="button" @click="showPassword = !showPassword" class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">
                      <EyeOff v-if="showPassword" class="h-4 w-4" />
                      <Eye v-else class="h-4 w-4" />
                    </button>
                  </div>
                </div>
                <div class="space-y-1">
                  <label class="text-[10px] font-bold uppercase tracking-widest text-slate-400 ml-1">Confirmation</label>
                  <div class="relative group">
                    <input v-model="formData.confirmPassword" :type="showConfirmPassword ? 'text' : 'password'" placeholder="••••••••"
                      :class="['w-full px-4 py-3.5 bg-slate-50 border rounded-2xl transition-all outline-none focus:ring-4 focus:ring-blue-50 focus:border-[#0070f3]', 
                      errors.confirmPassword ? 'border-red-300' : 'border-slate-200']" />
                  </div>
                </div>
              </div>

              <div class="pt-2">
                <label class="flex items-start gap-3 cursor-pointer group">
                  <input v-model="formData.acceptTerms" type="checkbox" class="mt-1 w-5 h-5 rounded border-slate-300 text-[#0070f3] focus:ring-[#0070f3]" />
                  <span class="text-xs text-slate-500 leading-relaxed group-hover:text-slate-700">
                    J'accepte les <router-link to="#" class="text-[#0070f3] font-bold">conditions d'utilisation</router-link> 
                    et la <router-link to="#" class="text-[#0070f3] font-bold">politique de confidentialité</router-link>.
                  </span>
                </label>
              </div>

              <button type="submit" :disabled="isLoading"
                class="w-full mt-4 py-4 bg-[#0070f3] text-white rounded-2xl font-bold text-lg hover:bg-blue-600 shadow-xl shadow-blue-100 flex items-center justify-center gap-3 disabled:opacity-70 transition-all active:scale-[0.98]">
                <span v-if="isLoading" class="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                <span v-else class="flex items-center gap-2">Créer mon compte <ArrowRight class="h-5 w-5" /></span>
              </button>
            </form>
          </div>

          <div class="bg-slate-50 p-6 border-t border-slate-100 text-center">
            <p class="text-sm text-slate-500 font-medium">
              Déjà membre ? 
              <router-link to="/connexion" class="text-[#0070f3] font-bold hover:underline underline-offset-4 ml-1">Se connecter</router-link>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// app/inscription/page.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Building2, Mail, Lock, Eye, EyeOff, User, Phone } from "lucide-react"

export default function RegisterPage() {
  const router = useRouter()
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    password: "",
    confirmPassword: "",
    acceptTerms: false,
  })
  const [errors, setErrors] = useState<Record<string, string>>({})

  const validate = () => {
    const newErrors: Record<string, string> = {}

    if (!formData.firstName) newErrors.firstName = "Le prenom est requis"
    if (!formData.lastName) newErrors.lastName = "Le nom est requis"
    if (!formData.email) newErrors.email = "L'email est requis"
    if (!formData.password) newErrors.password = "Le mot de passe est requis"
    if (formData.password.length < 8) newErrors.password = "Le mot de passe doit contenir au moins 8 caracteres"
    if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = "Les mots de passe ne correspondent pas"
    }
    if (!formData.acceptTerms) newErrors.acceptTerms = "Vous devez accepter les conditions"

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validate()) return

    setIsLoading(true)
    
    // Simulation d'inscription
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    router.push("/client")
    setIsLoading(false)
  }

  return (
    <div className="min-h-screen flex">
      {/* Left Side - Image */}
      <div className="hidden lg:block lg:w-1/2 bg-gradient-to-br from-sidebar to-sidebar/90 relative">
        <div className="absolute inset-0 flex items-center justify-center p-12">
          <div className="text-center text-sidebar-foreground">
            <Building2 className="h-20 w-20 mx-auto mb-6 text-sidebar-primary" />
            <h2 className="text-3xl font-bold mb-4">Rejoignez ImmoGestion</h2>
            <p className="text-sidebar-foreground/80 max-w-md">
              Creez votre compte gratuitement et accedez a notre catalogue de biens. 
              Reservez facilement et suivez vos demandes en temps reel.
            </p>
          </div>
        </div>
      </div>

      {/* Right Side - Form */}
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="w-full max-w-md">
          <Link href="/" className="inline-flex items-center gap-2 mb-8">
            <Building2 className="h-8 w-8 text-primary" />
            <span className="text-xl font-bold text-foreground">ImmoGestion</span>
          </Link>

          <h1 className="text-2xl font-bold text-foreground mb-2">Creer un compte</h1>
          <p className="text-muted-foreground mb-8">
            Inscrivez-vous pour commencer a chercher votre logement
          </p>

          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label htmlFor="firstName" className="block text-sm font-medium text-foreground mb-2">
                  Prenom
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                  <input
                    type="text"
                    id="firstName"
                    value={formData.firstName}
                    onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                    placeholder="Prenom"
                    className={`w-full pl-10 pr-4 py-3 bg-background border rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring ${
                      errors.firstName ? "border-destructive" : "border-input"
                    }`}
                  />
                </div>
                {errors.firstName && <p className="mt-1 text-sm text-destructive">{errors.firstName}</p>}
              </div>

              <div>
                <label htmlFor="lastName" className="block text-sm font-medium text-foreground mb-2">
                  Nom
                </label>
                <input
                  type="text"
                  id="lastName"
                  value={formData.lastName}
                  onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                  placeholder="Nom"
                  className={`w-full px-4 py-3 bg-background border rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring ${
                    errors.lastName ? "border-destructive" : "border-input"
                  }`}
                />
                {errors.lastName && <p className="mt-1 text-sm text-destructive">{errors.lastName}</p>}
              </div>
            </div>

            <div>
              <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                Adresse email
              </label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type="email"
                  id="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="votre@email.com"
                  className={`w-full pl-10 pr-4 py-3 bg-background border rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring ${
                    errors.email ? "border-destructive" : "border-input"
                  }`}
                />
              </div>
              {errors.email && <p className="mt-1 text-sm text-destructive">{errors.email}</p>}
            </div>

            <div>
              <label htmlFor="phone" className="block text-sm font-medium text-foreground mb-2">
                Telephone (optionnel)
              </label>
              <div className="relative">
                <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type="tel"
                  id="phone"
                  value={formData.phone}
                  onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                  placeholder="06 12 34 56 78"
                  className="w-full pl-10 pr-4 py-3 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-foreground mb-2">
                Mot de passe
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type={showPassword ? "text" : "password"}
                  id="password"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="Minimum 8 caracteres"
                  className={`w-full pl-10 pr-12 py-3 bg-background border rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring ${
                    errors.password ? "border-destructive" : "border-input"
                  }`}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  aria-label={showPassword ? "Masquer" : "Afficher"}
                >
                  {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
              {errors.password && <p className="mt-1 text-sm text-destructive">{errors.password}</p>}
            </div>

            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-foreground mb-2">
                Confirmer le mot de passe
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type={showConfirmPassword ? "text" : "password"}
                  id="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  placeholder="Confirmez votre mot de passe"
                  className={`w-full pl-10 pr-12 py-3 bg-background border rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring ${
                    errors.confirmPassword ? "border-destructive" : "border-input"
                  }`}
                />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  aria-label={showConfirmPassword ? "Masquer" : "Afficher"}
                >
                  {showConfirmPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
              {errors.confirmPassword && <p className="mt-1 text-sm text-destructive">{errors.confirmPassword}</p>}
            </div>

            <div>
              <label className="flex items-start gap-2">
                <input
                  type="checkbox"
                  checked={formData.acceptTerms}
                  onChange={(e) => setFormData({ ...formData, acceptTerms: e.target.checked })}
                  className="mt-1 w-4 h-4 rounded border-input text-primary focus:ring-ring"
                />
                <span className="text-sm text-muted-foreground">
                  J&apos;accepte les{" "}
                  <Link href="/conditions" className="text-primary hover:text-primary/80">
                    conditions d&apos;utilisation
                  </Link>{" "}
                  et la{" "}
                  <Link href="/confidentialite" className="text-primary hover:text-primary/80">
                    politique de confidentialite
                  </Link>
                </span>
              </label>
              {errors.acceptTerms && <p className="mt-1 text-sm text-destructive">{errors.acceptTerms}</p>}
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-3 bg-primary text-primary-foreground rounded-lg font-semibold hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? "Inscription en cours..." : "Creer mon compte"}
            </button>
          </form>

          <p className="mt-6 text-center text-muted-foreground">
            Deja un compte ?{" "}
            <Link href="/connexion" className="text-primary hover:text-primary/80 font-medium">
              Se connecter
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
