// frontend-vue/src/app/client/recherche/page.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Search, SlidersHorizontal, MapPin, Bed, Bath, Maximize, X, Calendar } from 'lucide-vue-next'
import DashboardHeader from '@/components/DashboardHeader.vue'
import { getList } from '@/lib/api'

const searchCity = ref('')
const priceMin = ref('')
const priceMax = ref('')
const surfaceMin = ref('')
const selectedOptions = ref<string[]>([])
const showFilters = ref(false)
const properties = ref<any[]>([])
const options = ref<any[]>([])

const availableProperties = computed(() => properties.value.filter((p) => p.status === 'disponible'))

const filteredProperties = computed(() => {
  let result = [...availableProperties.value]
  if (searchCity.value) {
    result = result.filter((p) => {
      const postalCode = p.postal_code || p.postalCode || ''
      return p.city.toLowerCase().includes(searchCity.value.toLowerCase()) || postalCode.includes(searchCity.value)
    })
  }
  if (priceMin.value) result = result.filter((p) => p.price >= Number(priceMin.value))
  if (priceMax.value) result = result.filter((p) => p.price <= Number(priceMax.value))
  if (surfaceMin.value) result = result.filter((p) => p.surface >= Number(surfaceMin.value))
  if (selectedOptions.value.length > 0) {
    result = result.filter((p) => selectedOptions.value.every((optId) => (p.options || []).some((opt: any) => opt.id === optId)))
  }
  return result
})

const toggleOption = (optionId: string) => {
  selectedOptions.value = selectedOptions.value.includes(optionId)
    ? selectedOptions.value.filter((id) => id !== optionId)
    : [...selectedOptions.value, optionId]
}

const clearFilters = () => {
  searchCity.value = ''
  priceMin.value = ''
  priceMax.value = ''
  surfaceMin.value = ''
  selectedOptions.value = []
}

const hasActiveFilters = computed(() => !!searchCity.value || !!priceMin.value || !!priceMax.value || !!surfaceMin.value || selectedOptions.value.length > 0)

onMounted(async () => {
  try {
    properties.value = await getList('/properties')
  } catch {
    properties.value = []
  }

  try {
    options.value = await getList('/options')
  } catch {
    options.value = []
  }
})
</script>

<template>
  <DashboardHeader title="Rechercher un bien" subtitle="Trouvez votre prochain logement" />

  <main class="flex-1 overflow-auto p-6">
    <div class="mb-6 rounded-xl border border-border bg-card p-4">
      <div class="flex flex-col gap-4 lg:flex-row">
        <div class="relative flex-1">
          <Search class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
          <input v-model="searchCity" type="text" placeholder="Rechercher par ville ou code postal..." class="w-full rounded-lg border border-input bg-background py-2.5 pl-10 pr-4" />
        </div>
        <button @click="showFilters = !showFilters" class="inline-flex items-center justify-center gap-2 rounded-lg border px-4 py-2.5" :class="showFilters || hasActiveFilters ? 'border-primary bg-primary text-primary-foreground' : 'border-input bg-background text-foreground'">
          <SlidersHorizontal class="h-5 w-5" />
          Filtres
          <span v-if="hasActiveFilters" class="rounded bg-primary-foreground px-1.5 py-0.5 text-xs font-medium text-primary">actif</span>
        </button>
      </div>

      <div v-if="showFilters" class="mt-4 border-t border-border pt-4">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-3 mb-4">
          <input v-model="priceMin" type="number" placeholder="Prix minimum" class="rounded-lg border border-input bg-background px-4 py-2.5" />
          <input v-model="priceMax" type="number" placeholder="Prix maximum" class="rounded-lg border border-input bg-background px-4 py-2.5" />
          <input v-model="surfaceMin" type="number" placeholder="Surface minimum" class="rounded-lg border border-input bg-background px-4 py-2.5" />
        </div>

        <div class="mb-4">
          <label class="mb-2 block text-sm font-medium text-foreground">Options</label>
          <div class="flex flex-wrap gap-2">
            <button v-for="option in options" :key="option.id" type="button" @click="toggleOption(option.id)" class="rounded-lg px-3 py-1.5 text-sm" :class="selectedOptions.includes(option.id) ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'">
              {{ option.name }}
            </button>
          </div>
        </div>

        <div class="flex justify-end">
          <button @click="clearFilters" class="inline-flex items-center gap-2 text-sm text-muted-foreground">
            <X class="h-4 w-4" /> Effacer les filtres
          </button>
        </div>
      </div>
    </div>

    <p class="mb-4 text-muted-foreground">{{ filteredProperties.length }} bien{{ filteredProperties.length > 1 ? 's' : '' }} disponible{{ filteredProperties.length > 1 ? 's' : '' }}</p>

    <div v-if="filteredProperties.length > 0" class="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
      <article v-for="property in filteredProperties" :key="property.id" class="overflow-hidden rounded-xl border border-border bg-card">
        <div class="relative h-48">
          <img :src="property.images?.[0] || '/placeholder.svg'" :alt="property.title" class="h-full w-full object-cover" />
          <div class="absolute bottom-3 left-3 rounded-lg bg-primary px-3 py-1 text-sm font-semibold text-primary-foreground">{{ property.price.toLocaleString() }} FCFA/nuit</div>
        </div>
        <div class="p-4">
          <h3 class="mb-2 font-semibold text-foreground">{{ property.title }}</h3>
          <div class="mb-3 flex items-center gap-1 text-sm text-muted-foreground"><MapPin class="h-4 w-4" />{{ property.city }}</div>
          <div class="mb-4 flex items-center gap-4 text-sm text-muted-foreground">
            <div class="flex items-center gap-1"><Maximize class="h-4 w-4" />{{ property.surface }} m2</div>
            <div class="flex items-center gap-1"><Bed class="h-4 w-4" />{{ property.bedrooms ?? 0 }}</div>
            <div class="flex items-center gap-1"><Bath class="h-4 w-4" />{{ property.bathrooms ?? 0 }}</div>
          </div>
          <div class="flex gap-2">
            <RouterLink :to="`/biens/${property.id}`" class="flex-1 rounded-lg border border-input px-4 py-2 text-center text-sm font-medium text-foreground">Voir details</RouterLink>
            <RouterLink :to="`/client/reservations/nouvelle?bien=${property.id}`" class="flex-1 inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"><Calendar class="h-4 w-4" />Reserver</RouterLink>
          </div>
        </div>
      </article>
    </div>

    <div v-else class="rounded-xl border border-border bg-card py-16 text-center">
      <Search class="mx-auto mb-4 h-12 w-12 text-muted-foreground" />
      <h3 class="mb-2 text-lg font-semibold text-foreground">Aucun bien trouve</h3>
      <p class="mb-4 text-muted-foreground">Essayez de modifier vos criteres de recherche</p>
      <button @click="clearFilters" class="font-medium text-primary">Effacer tous les filtres</button>
    </div>
  </main>
</template>

// app/client/recherche/page.tsx
"use client"

import { useState, useMemo } from "react"
import Link from "next/link"
import Image from "next/image"
import { Search, SlidersHorizontal, MapPin, Bed, Bath, Maximize, X, Calendar } from "lucide-react"
import { DashboardHeader } from "@/components/dashboard-header"
import { mockProperties, mockOptions } from "@/lib/mock-data"

export default function ClientSearchPage() {
  const [searchCity, setSearchCity] = useState("")
  const [priceMin, setPriceMin] = useState("")
  const [priceMax, setPriceMax] = useState("")
  const [surfaceMin, setSurfaceMin] = useState("")
  const [selectedOptions, setSelectedOptions] = useState<string[]>([])
  const [showFilters, setShowFilters] = useState(false)

  const availableProperties = mockProperties.filter(p => p.status === "disponible")

  const filteredProperties = useMemo(() => {
    let result = [...availableProperties]

    if (searchCity) {
      result = result.filter(p =>
        p.city.toLowerCase().includes(searchCity.toLowerCase()) ||
        p.postalCode.includes(searchCity)
      )
    }

    if (priceMin) {
      result = result.filter(p => p.price >= Number(priceMin))
    }

    if (priceMax) {
      result = result.filter(p => p.price <= Number(priceMax))
    }

    if (surfaceMin) {
      result = result.filter(p => p.surface >= Number(surfaceMin))
    }

    if (selectedOptions.length > 0) {
      result = result.filter(p =>
        selectedOptions.every(optId => p.options.some(opt => opt.id === optId))
      )
    }

    return result
  }, [availableProperties, searchCity, priceMin, priceMax, surfaceMin, selectedOptions])

  const toggleOption = (optionId: string) => {
    setSelectedOptions(prev =>
      prev.includes(optionId)
        ? prev.filter(id => id !== optionId)
        : [...prev, optionId]
    )
  }

  const clearFilters = () => {
    setSearchCity("")
    setPriceMin("")
    setPriceMax("")
    setSurfaceMin("")
    setSelectedOptions([])
  }

  const hasActiveFilters = searchCity || priceMin || priceMax || surfaceMin || selectedOptions.length > 0

  return (
    <>
      <DashboardHeader title="Rechercher un bien" subtitle="Trouvez votre prochain logement" />

      <main className="flex-1 p-6 overflow-auto">
        {/* Search Bar */}
        <div className="bg-card rounded-xl border border-border p-4 mb-6">
          <div className="flex flex-col lg:flex-row gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <input
                type="text"
                placeholder="Rechercher par ville ou code postal..."
                value={searchCity}
                onChange={(e) => setSearchCity(e.target.value)}
                className="w-full pl-10 pr-4 py-2.5 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>

            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg border transition-colors ${
                showFilters || hasActiveFilters
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-background border-input text-foreground hover:bg-muted"
              }`}
            >
              <SlidersHorizontal className="h-5 w-5" />
              Filtres
              {hasActiveFilters && (
                <span className="bg-primary-foreground text-primary px-1.5 py-0.5 rounded text-xs font-medium">
                  {(searchCity ? 1 : 0) + (priceMin ? 1 : 0) + (priceMax ? 1 : 0) + (surfaceMin ? 1 : 0) + selectedOptions.length}
                </span>
              )}
            </button>
          </div>

          {/* Extended Filters */}
          {showFilters && (
            <div className="mt-4 pt-4 border-t border-border">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Prix minimum</label>
                  <input
                    type="number"
                    placeholder="Min EUR/mois"
                    value={priceMin}
                    onChange={(e) => setPriceMin(e.target.value)}
                    className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Prix maximum</label>
                  <input
                    type="number"
                    placeholder="Max EUR/mois"
                    value={priceMax}
                    onChange={(e) => setPriceMax(e.target.value)}
                    className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Surface minimum</label>
                  <input
                    type="number"
                    placeholder="Min m2"
                    value={surfaceMin}
                    onChange={(e) => setSurfaceMin(e.target.value)}
                    className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                </div>
              </div>

              <div className="mb-4">
                <label className="block text-sm font-medium text-foreground mb-2">Options</label>
                <div className="flex flex-wrap gap-2">
                  {mockOptions.map((option) => (
                    <button
                      key={option.id}
                      onClick={() => toggleOption(option.id)}
                      className={`px-3 py-1.5 rounded-lg text-sm transition-colors ${
                        selectedOptions.includes(option.id)
                          ? "bg-primary text-primary-foreground"
                          : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
                      }`}
                    >
                      {option.name}
                    </button>
                  ))}
                </div>
              </div>

              {hasActiveFilters && (
                <div className="flex justify-end">
                  <button
                    onClick={clearFilters}
                    className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <X className="h-4 w-4" />
                    Effacer les filtres
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Results Count */}
        <p className="text-muted-foreground mb-4">
          {filteredProperties.length} bien{filteredProperties.length > 1 ? "s" : ""} disponible{filteredProperties.length > 1 ? "s" : ""}
        </p>

        {/* Properties Grid */}
        {filteredProperties.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {filteredProperties.map((property) => (
              <article key={property.id} className="bg-card rounded-xl border border-border overflow-hidden hover:shadow-lg transition-shadow">
                <div className="relative h-48">
                  <Image
                    src={property.images[0] || "/placeholder.svg"}
                    alt={property.title}
                    fill
                    className="object-cover"
                  />
                  <div className="absolute bottom-3 left-3 px-3 py-1 bg-primary text-primary-foreground rounded-lg font-semibold text-sm">
                    {property.price.toLocaleString()} EUR/mois
                  </div>
                </div>

                <div className="p-4">
                  <h3 className="font-semibold text-foreground mb-2 line-clamp-1">{property.title}</h3>
                  
                  <div className="flex items-center gap-1 text-muted-foreground text-sm mb-3">
                    <MapPin className="h-4 w-4" />
                    <span>{property.city}</span>
                  </div>

                  <div className="flex items-center gap-4 text-muted-foreground text-sm mb-4">
                    <div className="flex items-center gap-1">
                      <Maximize className="h-4 w-4" />
                      <span>{property.surface} m2</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Bed className="h-4 w-4" />
                      <span>{property.bedrooms}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Bath className="h-4 w-4" />
                      <span>{property.bathrooms}</span>
                    </div>
                  </div>

                  {property.options.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-4">
                      {property.options.slice(0, 3).map((option) => (
                        <span
                          key={option.id}
                          className="px-2 py-0.5 bg-secondary text-secondary-foreground rounded text-xs"
                        >
                          {option.name}
                        </span>
                      ))}
                      {property.options.length > 3 && (
                        <span className="px-2 py-0.5 bg-secondary text-secondary-foreground rounded text-xs">
                          +{property.options.length - 3}
                        </span>
                      )}
                    </div>
                  )}

                  <div className="flex gap-2">
                    <Link
                      href={`/biens/${property.id}`}
                      className="flex-1 text-center px-4 py-2 border border-input rounded-lg text-sm font-medium text-foreground hover:bg-muted transition-colors"
                    >
                      Voir details
                    </Link>
                    <Link
                      href={`/client/reservations/nouvelle?bien=${property.id}`}
                      className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition-colors"
                    >
                      <Calendar className="h-4 w-4" />
                      Reserver
                    </Link>
                  </div>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="text-center py-16 bg-card rounded-xl border border-border">
            <Search className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-foreground mb-2">Aucun bien trouve</h3>
            <p className="text-muted-foreground mb-4">
              Essayez de modifier vos criteres de recherche
            </p>
            <button
              onClick={clearFilters}
              className="text-primary hover:text-primary/80 font-medium"
            >
              Effacer tous les filtres
            </button>
          </div>
        )}
      </main>
    </>
  )
}
