// frontend-vue/src/app/agent/biens/[id]/page.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowLeft, Edit, Trash2, MapPin, Bed, Bath, Users, Maximize, Wifi, Car, Waves, Wind, Tv, UtensilsCrossed, CalendarDays, CheckCircle2, XCircle, Clock } from 'lucide-vue-next'
import { getDetail, getList } from '@/lib/api'

const route = useRoute()
const property = ref<any | null>(null)
const propertyReservations = ref<any[]>([])
const propertyOptions = computed(() => property.value?.options ?? [])

const iconMap: Record<string, any> = { wifi: Wifi, car: Car, waves: Waves, wind: Wind, tv: Tv, utensils: UtensilsCrossed }
const statusLabels: Record<string, string> = { disponible: 'Disponible', reserve: 'Réservé', maintenance: 'Maintenance' }
const statusClasses: Record<string, string> = { disponible: 'px-2.5 py-0.5 rounded-full text-xs font-semibold bg-green-100 text-green-700', reserve: 'px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-100 text-blue-700', maintenance: 'px-2.5 py-0.5 rounded-full text-xs font-semibold bg-slate-100 text-slate-700' }
const reservationLabels: Record<string, string> = { confirmee: 'Confirmée', en_attente: 'En attente', refusee: 'Refusée' }
const reservationIcons: Record<string, any> = { confirmee: CheckCircle2, en_attente: Clock, refusee: XCircle }
const reservationStatusClasses: Record<string, string> = { confirmee: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-700', en_attente: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-700', refusee: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-700' }

const mainStats = computed(() => [
  { label: 'Surface', value: `${property.value?.surface ?? 0} m²`, icon: Maximize },
  { label: 'Chambres', value: property.value?.bedrooms ?? 0, icon: Bed },
  { label: 'Salles de bain', value: property.value?.bathrooms ?? 0, icon: Bath },
  { label: 'Capacité', value: `${property.value?.capacity ?? 0} pers.`, icon: Users },
])

const sideStats = computed(() => {
  const confirmed = propertyReservations.value.filter((reservation) => reservation.status === 'confirmee')
  const totalRevenue = confirmed.reduce((sum, reservation) => sum + reservation.totalPrice, 0)

  return [
    { label: 'Total réservations', value: propertyReservations.value.length },
    { label: 'Confirmées', value: confirmed.length, color: 'text-green-600' },
    { label: 'En attente', value: propertyReservations.value.filter((reservation) => reservation.status === 'en_attente').length, color: 'text-amber-600' },
    { label: 'Revenus totaux', value: formatPrice(totalRevenue) },
  ]
})

const getClientName = (clientId: string) => {
  const client = propertyReservations.value.find((item) => item.client?.id === clientId)?.client
  return client ? `${client.first_name || client.firstName || ''} ${client.last_name || client.lastName || ''}`.trim() : 'Client inconnu'
}

const formatDate = (date: Date) => date.toLocaleDateString('fr-FR')
const formatPrice = (price: number) => `${price.toLocaleString()} FCFA`

onMounted(async () => {
  try {
    property.value = await getDetail('/properties', String(route.params.id))
  } catch {
    property.value = null
  }

  try {
    const reservations = await getList('/reservations')
    propertyReservations.value = reservations.filter((reservation: any) => String(reservation.property_id || reservation.propertyId) === String(route.params.id))
  } catch {
    propertyReservations.value = []
  }
})
</script>

<template>
  <div v-if="!property" class="flex flex-col items-center justify-center py-12">
    <h1 class="text-2xl font-bold text-slate-900">Bien non trouvé</h1>
    <RouterLink to="/agent/biens" class="mt-4 rounded-md bg-blue-600 px-4 py-2 text-white">Retour à la liste</RouterLink>
  </div>

  <div v-else class="space-y-6 p-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex items-center gap-4">
        <RouterLink to="/agent/biens" class="rounded-full border border-slate-200 p-2 transition-colors hover:bg-slate-100">
          <ArrowLeft class="h-5 w-5 text-slate-600" />
        </RouterLink>
        <div>
          <h1 class="text-3xl font-bold text-slate-900">{{ property.title }}</h1>
          <div class="mt-1 flex items-center gap-2 text-slate-500">
            <MapPin class="h-4 w-4" />
            <span>{{ property.address }}, {{ property.city }}</span>
          </div>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <RouterLink :to="`/agent/biens/${property.id}/modifier`" class="inline-flex items-center rounded-lg border border-slate-300 px-4 py-2 transition-colors hover:bg-slate-50">
          <Edit class="mr-2 h-4 w-4" /> Modifier
        </RouterLink>
        <button class="inline-flex items-center rounded-lg bg-red-600 px-4 py-2 text-white transition-colors hover:bg-red-700">
          <Trash2 class="mr-2 h-4 w-4" /> Supprimer
        </button>
      </div>
    </div>

    <div class="grid gap-4 md:grid-cols-3">
      <div class="aspect-video overflow-hidden rounded-xl bg-slate-100 md:col-span-2">
        <img :src="property.images[0]" :alt="property.title" class="h-full w-full object-cover" />
      </div>
      <div class="grid grid-cols-2 gap-4 md:grid-cols-1">
        <div v-for="(image, index) in property.images.slice(1, 3)" :key="index" class="aspect-video overflow-hidden rounded-xl bg-slate-100">
          <img :src="image" alt="" class="h-full w-full object-cover" />
        </div>
      </div>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
      <div class="space-y-6 lg:col-span-2">
        <div class="rounded-xl border border-slate-200 bg-white shadow-sm">
          <div class="flex items-center justify-between border-b border-slate-100 p-6">
            <h3 class="text-lg font-bold text-slate-900">Informations</h3>
            <span :class="statusClasses[property.status]">{{ statusLabels[property.status] }}</span>
          </div>
          <div class="space-y-6 p-6">
            <div class="grid gap-4 sm:grid-cols-4">
              <div v-for="stat in mainStats" :key="stat.label" class="flex items-center gap-2 rounded-lg border border-slate-100 bg-slate-50 p-3">
                <component :is="stat.icon" class="h-5 w-5 text-blue-600" />
                <div>
                  <p class="text-xs text-slate-500">{{ stat.label }}</p>
                  <p class="font-bold text-slate-900">{{ stat.value }}</p>
                </div>
              </div>
            </div>

            <div>
              <h4 class="mb-2 font-bold text-slate-900">Description</h4>
              <p class="leading-relaxed text-slate-600">{{ property.description }}</p>
            </div>
          </div>
        </div>

        <div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <h3 class="mb-4 text-lg font-bold text-slate-900">Équipements et options</h3>
          <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
            <div v-for="option in propertyOptions" :key="option.id" class="flex items-center gap-2 rounded-lg border border-slate-100 bg-white p-3">
              <component :is="iconMap[option.icon] || Wifi" class="h-5 w-5 text-blue-600" />
              <span class="text-sm font-medium text-slate-700">{{ option.name }}</span>
            </div>
          </div>
        </div>

        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
          <div class="border-b border-slate-100 p-6">
            <h3 class="flex items-center gap-2 text-lg font-bold text-slate-900">
              <CalendarDays class="h-5 w-5 text-blue-600" />
              Historique des réservations
            </h3>
            <p class="text-sm text-slate-500">{{ propertyReservations.length }} réservation(s) pour ce bien</p>
          </div>
          <div class="p-6">
            <div v-if="propertyReservations.length === 0" class="py-8 text-center text-slate-400">Aucune réservation pour ce bien</div>
            <div v-else class="space-y-3">
              <div v-for="reservation in propertyReservations" :key="reservation.id" class="flex items-center justify-between rounded-lg border border-slate-100 p-4 transition-colors hover:bg-slate-50">
                <div>
                  <p class="font-bold text-slate-900">{{ getClientName(reservation.clientId) }}</p>
                  <p class="text-sm text-slate-500">{{ formatDate(reservation.startDate) }} - {{ formatDate(reservation.endDate) }}</p>
                </div>
                <div class="flex items-center gap-4">
                  <span class="font-bold text-slate-900">{{ formatPrice(reservation.totalPrice) }}</span>
                  <span :class="reservationStatusClasses[reservation.status]">
                    <component :is="reservationIcons[reservation.status]" class="mr-1.5 h-3.5 w-3.5" />
                    {{ reservationLabels[reservation.status] }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="space-y-6">
        <div class="rounded-xl border border-slate-200 bg-white p-6 text-center shadow-sm">
          <h3 class="mb-2 text-sm font-medium uppercase tracking-wider text-slate-500">Tarification</h3>
          <p class="text-4xl font-black text-blue-600">{{ formatPrice(property.pricePerNight) }}</p>
          <p class="mt-1 text-sm text-slate-400">FCFA / nuit</p>
        </div>

        <div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <h3 class="mb-4 text-lg font-bold text-slate-900">Statistiques</h3>
          <div class="space-y-4">
            <div v-for="stat in sideStats" :key="stat.label" class="flex items-center justify-between border-b border-slate-50 py-2 last:border-0">
              <span class="text-slate-500">{{ stat.label }}</span>
              <span class="font-bold" :class="stat.color || 'text-slate-900'">{{ stat.value }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// app/agent/biens/[id]/page.tsx
"use client"

import { use } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { 
  ArrowLeft, 
  Edit, 
  Trash2, 
  MapPin, 
  Bed, 
  Bath, 
  Users, 
  Maximize,
  Wifi,
  Car,
  Waves,
  Wind,
  Tv,
  UtensilsCrossed,
  CalendarDays,
  CheckCircle2,
  XCircle,
  Clock
} from "lucide-react"
import Link from "next/link"
import { mockProperties, mockReservations, mockClients, mockOptions } from "@/lib/mock-data"

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  wifi: Wifi,
  car: Car,
  waves: Waves,
  wind: Wind,
  tv: Tv,
  utensils: UtensilsCrossed,
}

export default function PropertyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const property = mockProperties.find(p => p.id === id)
  
  if (!property) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <h1 className="text-2xl font-bold">Bien non trouvé</h1>
        <Button className="mt-4" asChild>
          <Link href="/agent/biens">Retour à la liste</Link>
        </Button>
      </div>
    )
  }

  const propertyReservations = mockReservations.filter(r => r.propertyId === property.id)
  const propertyOptions = property.options

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link href="/agent/biens">
              <ArrowLeft className="h-5 w-5" />
            </Link>
          </Button>
          <div>
            <h1 className="text-3xl font-bold text-foreground">{property.title}</h1>
            <div className="flex items-center gap-2 mt-1 text-muted-foreground">
              <MapPin className="h-4 w-4" />
              <span>{property.address}, {property.city}</span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" asChild>
            <Link href={`/agent/biens/${property.id}/modifier`}>
              <Edit className="mr-2 h-4 w-4" />
              Modifier
            </Link>
          </Button>
          <Button variant="destructive">
            <Trash2 className="mr-2 h-4 w-4" />
            Supprimer
          </Button>
        </div>
      </div>

      {/* Galerie photos */}
      <div className="grid gap-4 md:grid-cols-3">
        <div className="md:col-span-2 aspect-video rounded-xl overflow-hidden">
          <img 
            src={property.images[0]} 
            alt={property.title}
            className="w-full h-full object-cover"
          />
        </div>
        <div className="grid grid-cols-2 md:grid-cols-1 gap-4">
          {property.images.slice(1, 3).map((img, idx) => (
            <div key={idx} className="aspect-video rounded-xl overflow-hidden">
              <img src={img} alt="" className="w-full h-full object-cover" />
            </div>
          ))}
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          {/* Informations principales */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Informations</CardTitle>
                <Badge variant={
                  property.status === "disponible" ? "default" :
                  property.status === "reserve" ? "secondary" : "outline"
                }>
                  {property.status === "disponible" ? "Disponible" :
                   property.status === "reserve" ? "Réservé" : "Maintenance"}
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                <div className="flex items-center gap-2 p-3 rounded-lg bg-muted">
                  <Maximize className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Surface</p>
                    <p className="font-medium">{property.surface} m²</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 p-3 rounded-lg bg-muted">
                  <Bed className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Chambres</p>
                    <p className="font-medium">{property.bedrooms}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 p-3 rounded-lg bg-muted">
                  <Bath className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Salles de bain</p>
                    <p className="font-medium">{property.bathrooms}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 p-3 rounded-lg bg-muted">
                  <Users className="h-5 w-5 text-primary" />
                  <div>
                    <p className="text-sm text-muted-foreground">Capacité</p>
                    <p className="font-medium">{property.capacity} pers.</p>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-medium mb-2">Description</h4>
                <p className="text-muted-foreground">{property.description}</p>
              </div>
            </CardContent>
          </Card>

          {/* Options */}
          <Card>
            <CardHeader>
              <CardTitle>Équipements et options</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {propertyOptions.map((option) => {
                  const Icon = (option.icon && iconMap[option.icon]) || Wifi
                  return (
                    <div key={option.id} className="flex items-center gap-2 p-3 rounded-lg border">
                      <Icon className="h-5 w-5 text-primary" />
                      <span className="text-sm font-medium">{option.name}</span>
                    </div>
                  )
                })}
              </div>
            </CardContent>
          </Card>

          {/* Historique des réservations */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CalendarDays className="h-5 w-5" />
                Historique des réservations
              </CardTitle>
              <CardDescription>
                {propertyReservations.length} réservation(s) pour ce bien
              </CardDescription>
            </CardHeader>
            <CardContent>
              {propertyReservations.length === 0 ? (
                <p className="text-muted-foreground text-center py-8">
                  Aucune réservation pour ce bien
                </p>
              ) : (
                <div className="space-y-3">
                  {propertyReservations.map((reservation) => {
                    const client = mockClients.find(c => c.id === reservation.clientId)
                    return (
                      <div 
                        key={reservation.id}
                        className="flex items-center justify-between p-4 rounded-lg border"
                      >
                        <div>
                          <p className="font-medium">
                            {client?.firstName} {client?.lastName}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {new Date(reservation.startDate).toLocaleDateString('fr-FR')} - {new Date(reservation.endDate).toLocaleDateString('fr-FR')}
                          </p>
                        </div>
                        <div className="flex items-center gap-3">
                          <span className="font-medium">{reservation.totalPrice.toLocaleString()} FCFA</span>
                          <Badge variant={
                            reservation.status === "confirmee" ? "default" :
                            reservation.status === "en_attente" ? "secondary" : "destructive"
                          }>
                            {reservation.status === "confirmee" && <CheckCircle2 className="mr-1 h-3 w-3" />}
                            {reservation.status === "en_attente" && <Clock className="mr-1 h-3 w-3" />}
                            {reservation.status === "refusee" && <XCircle className="mr-1 h-3 w-3" />}
                            {reservation.status === "confirmee" ? "Confirmée" :
                             reservation.status === "en_attente" ? "En attente" : "Refusée"}
                          </Badge>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Tarification</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center">
                <p className="text-4xl font-bold text-primary">
                  {property.pricePerNight.toLocaleString()}
                </p>
                <p className="text-muted-foreground">FCFA / nuit</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Statistiques</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground">Total réservations</span>
                <span className="font-medium">{propertyReservations.length}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground">Confirmées</span>
                <span className="font-medium text-green-600">
                  {propertyReservations.filter(r => r.status === "confirmee").length}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground">En attente</span>
                <span className="font-medium text-orange-600">
                  {propertyReservations.filter(r => r.status === "en_attente").length}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground">Revenus totaux</span>
                <span className="font-medium">
                  {propertyReservations
                    .filter(r => r.status === "confirmee")
                    .reduce((sum, r) => sum + r.totalPrice, 0)
                    .toLocaleString()} FCFA
                </span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Actions rapides</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <Button className="w-full" variant="outline" asChild>
                <Link href={`/agent/biens/${property.id}/modifier`}>
                  <Edit className="mr-2 h-4 w-4" />
                  Modifier le bien
                </Link>
              </Button>
              <Button className="w-full" variant="outline">
                Changer le statut
              </Button>
              <Button className="w-full" variant="destructive">
                <Trash2 className="mr-2 h-4 w-4" />
                Supprimer
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
