// frontend-vue/src/app/agent/biens/[id]/modifier/page.vue
<template>
  <div v-if="!property" class="flex flex-col items-center justify-center py-12">
    <h1 class="text-2xl font-bold">Bien non trouvé</h1>
    <router-link to="/agent/biens" class="mt-4 px-4 py-2 bg-blue-600 text-white rounded-md">
      Retour à la liste
    </router-link>
  </div>

  <div v-else class="space-y-6 p-6">
    <div class="flex items-center gap-4">
      <router-link :to="`/agent/biens/${property.id}`" class="p-2 hover:bg-slate-100 rounded-full transition-colors">
        <ArrowLeft class="h-5 w-5 text-slate-600" />
      </router-link>
      <div>
        <h1 class="text-3xl font-bold text-slate-900">Modifier le bien</h1>
        <p class="text-slate-500 mt-1">{{ property.title }}</p>
      </div>
    </div>

    <form @submit.prevent="handleSubmit" class="space-y-6">
      <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div class="p-6 border-b border-slate-100">
          <h3 class="font-bold text-slate-900 flex items-center gap-2">
            <Building2 class="h-5 w-5 text-blue-600" />
            Informations générales
          </h3>
        </div>
        <div class="p-6 space-y-4">
          <div class="grid gap-4 sm:grid-cols-2">
            <div class="space-y-2">
              <label class="text-sm font-medium text-slate-700">Titre du bien *</label>
              <input v-model="formData.title" type="text" class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 outline-none" />
            </div>
            <div class="space-y-2">
              <label class="text-sm font-medium text-slate-700">Type de bien *</label>
              <select v-model="formData.type" class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 outline-none">
                <option value="villa">Villa</option>
                <option value="appartement">Appartement</option>
                <option value="studio">Studio</option>
                <option value="maison">Maison</option>
                <option value="duplex">Duplex</option>
              </select>
            </div>
          </div>

          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Description *</label>
            <textarea v-model="formData.description" rows="4" class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 outline-none"></textarea>
          </div>

          <div class="grid gap-4 sm:grid-cols-2">
            <div class="space-y-2">
              <label class="text-sm font-medium text-slate-700">Adresse *</label>
              <input v-model="formData.address" type="text" class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 outline-none" />
            </div>
            <div class="space-y-2">
              <label class="text-sm font-medium text-slate-700">Ville *</label>
              <select v-model="formData.city" class="w-full px-3 py-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-blue-500 outline-none">
                <option value="abidjan">Abidjan</option>
                <option value="bouake">Bouaké</option>
                <option value="yamoussoukro">Yamoussoukro</option>
                <option value="san-pedro">San Pedro</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <h3 class="font-bold text-slate-900 mb-4">Caractéristiques</h3>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Surface (m²) *</label>
            <input v-model="formData.surface" type="number" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Chambres *</label>
            <input v-model="formData.bedrooms" type="number" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Salles de bain *</label>
            <input v-model="formData.bathrooms" type="number" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Capacité (pers.) *</label>
            <input v-model="formData.capacity" type="number" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none" />
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <h3 class="font-bold text-slate-900 mb-4">Tarification</h3>
        <div class="grid gap-4 sm:grid-cols-2">
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Prix par nuit (FCFA) *</label>
            <input v-model="formData.pricePerNight" type="number" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-700">Statut *</label>
            <select v-model="formData.status" class="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none">
              <option value="disponible">Disponible</option>
              <option value="reserve">Réservé</option>
              <option value="maintenance">En maintenance</option>
            </select>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <h3 class="font-bold text-slate-900 mb-4">Options et équipements</h3>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <div v-for="option in mockOptions" :key="option.id" class="flex items-center space-x-3">
            <input 
              type="checkbox" 
              :id="option.id" 
              :value="option.id" 
              v-model="formData.options"
              class="w-4 h-4 text-blue-600 rounded border-slate-300 focus:ring-blue-500"
            />
            <label :for="option.id" class="text-sm font-medium text-slate-700 cursor-pointer">
              {{ option.name }}
            </label>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <h3 class="font-bold text-slate-900 mb-4">Photos du bien</h3>
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
          <div v-for="(img, idx) in formData.images" :key="idx" class="relative aspect-video rounded-lg overflow-hidden bg-slate-100">
            <img :src="img" class="w-full h-full object-cover" />
            <button 
              type="button" 
              @click="removeImage(idx)"
              class="absolute top-2 right-2 p-1 bg-red-600 text-white rounded-full hover:bg-red-700 shadow-lg"
            >
              <X class="h-3 w-3" />
            </button>
          </div>
        </div>
        <div class="border-2 border-dashed border-slate-200 rounded-lg p-8 text-center hover:border-blue-400 transition-colors cursor-pointer">
          <Upload class="h-8 w-8 mx-auto text-slate-400 mb-2" />
          <p class="text-sm text-slate-500 mb-2">Cliquez pour ajouter des photos</p>
          <button type="button" class="text-sm font-semibold text-blue-600">Parcourir les fichiers</button>
        </div>
      </div>

      <div class="flex items-center justify-end gap-4">
        <router-link :to="`/agent/biens/${property?.id}`" class="px-6 py-2 border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors">
          Annuler
        </router-link>
        <button 
          type="submit" 
          class="flex items-center gap-2 px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 shadow-sm transition-colors"
        >
          <Save class="h-4 w-4" />
          Enregistrer les modifications
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { ArrowLeft, Upload, X, Save, Building2 } from 'lucide-vue-next'

// Simulation des props ou de la récupération d'ID (via vue-router ou inertia)
const props = defineProps<{ id: string }>()

// MOCK DATA (À importer de ton fichier lib)
const mockOptions = [
  { id: 'wifi', name: 'Wi-Fi' },
  { id: 'pool', name: 'Piscine' },
  { id: 'climatisation', name: 'Climatisation' },
  { id: 'parking', name: 'Parking' },
  { id: 'cuisine', name: 'Cuisine équipée' },
]

// Simulation d'un bien trouvé
const property = ref({
  id: '1',
  title: 'Villa de Luxe avec Piscine',
  type: 'villa',
  description: 'Une magnifique villa située au coeur de la ville...',
  address: 'Rues des Jardins',
  city: 'abidjan',
  surface: 250,
  bedrooms: 4,
  bathrooms: 3,
  capacity: 8,
  pricePerNight: 150000,
  status: 'disponible',
  options: ['wifi', 'pool'],
  images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800']
})

// État local réactif pour le formulaire
const formData = reactive({ ...property.value })

const removeImage = (index: number) => {
  formData.images.splice(index, 1)
}

const handleSubmit = () => {
  console.log("Données envoyées :", formData)
  // Ici : axios.put(`/api/properties/${property.value.id}`, formData)
}
</script>

// app/agent/biens/[id]/modifier/page.tsx
"use client"

import { use, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { ArrowLeft, Upload, X, Save, Building2 } from "lucide-react"
import Link from "next/link"
import { mockProperties, mockOptions } from "@/lib/mock-data"

export default function EditPropertyPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const property = mockProperties.find(p => p.id === id)
  
  const [selectedOptions, setSelectedOptions] = useState<string[]>(property?.options || [])
  const [images, setImages] = useState<string[]>(property?.images || [])

  if (!property) {
    return (
      <div className="flex flex-col items-center justify-center py-12">
        <h1 className="text-2xl font-bold">Bien non trouvé</h1>
        <Button className="mt-4" asChild>
          <Link href="/agent/biens">Retour à la liste</Link>
        </Button>
      </div>
    )
  }

  const handleOptionToggle = (optionId: string) => {
    setSelectedOptions(prev => 
      prev.includes(optionId) 
        ? prev.filter(id => id !== optionId)
        : [...prev, optionId]
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href={`/agent/biens/${property.id}`}>
            <ArrowLeft className="h-5 w-5" />
          </Link>
        </Button>
        <div>
          <h1 className="text-3xl font-bold text-foreground">Modifier le bien</h1>
          <p className="text-muted-foreground mt-1">
            {property.title}
          </p>
        </div>
      </div>

      <form className="space-y-6">
        {/* Informations générales */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Building2 className="h-5 w-5" />
              Informations générales
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="title">Titre du bien *</Label>
                <Input id="title" defaultValue={property.title} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="type">Type de bien *</Label>
                <Select defaultValue={property.type}>
                  <SelectTrigger id="type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="villa">Villa</SelectItem>
                    <SelectItem value="appartement">Appartement</SelectItem>
                    <SelectItem value="studio">Studio</SelectItem>
                    <SelectItem value="maison">Maison</SelectItem>
                    <SelectItem value="duplex">Duplex</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Description *</Label>
              <Textarea 
                id="description" 
                defaultValue={property.description}
                rows={4}
              />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="address">Adresse *</Label>
                <Input id="address" defaultValue={property.address} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="city">Ville *</Label>
                <Select defaultValue={property.city.toLowerCase()}>
                  <SelectTrigger id="city">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="abidjan">Abidjan</SelectItem>
                    <SelectItem value="bouake">Bouaké</SelectItem>
                    <SelectItem value="yamoussoukro">Yamoussoukro</SelectItem>
                    <SelectItem value="san-pedro">San Pedro</SelectItem>
                    <SelectItem value="korhogo">Korhogo</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Caractéristiques */}
        <Card>
          <CardHeader>
            <CardTitle>Caractéristiques</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <div className="space-y-2">
                <Label htmlFor="surface">Surface (m²) *</Label>
                <Input id="surface" type="number" defaultValue={property.surface} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="bedrooms">Chambres *</Label>
                <Input id="bedrooms" type="number" defaultValue={property.bedrooms} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="bathrooms">Salles de bain *</Label>
                <Input id="bathrooms" type="number" defaultValue={property.bathrooms} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="capacity">Capacité (pers.) *</Label>
                <Input id="capacity" type="number" defaultValue={property.capacity} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Tarification */}
        <Card>
          <CardHeader>
            <CardTitle>Tarification</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="price">Prix par nuit (FCFA) *</Label>
                <Input id="price" type="number" defaultValue={property.pricePerNight} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="status">Statut *</Label>
                <Select defaultValue={property.status}>
                  <SelectTrigger id="status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="disponible">Disponible</SelectItem>
                    <SelectItem value="reserve">Réservé</SelectItem>
                    <SelectItem value="maintenance">En maintenance</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Options */}
        <Card>
          <CardHeader>
            <CardTitle>Options et équipements</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {mockOptions.map((option) => (
                <div key={option.id} className="flex items-center space-x-3">
                  <Checkbox
                    id={option.id}
                    checked={selectedOptions.includes(option.id)}
                    onCheckedChange={() => handleOptionToggle(option.id)}
                  />
                  <label
                    htmlFor={option.id}
                    className="text-sm font-medium leading-none cursor-pointer"
                  >
                    {option.name}
                  </label>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Images */}
        <Card>
          <CardHeader>
            <CardTitle>Photos du bien</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
              {images.map((img, idx) => (
                <div key={idx} className="relative aspect-video rounded-lg overflow-hidden bg-muted">
                  <img src={img} alt="" className="w-full h-full object-cover" />
                  <Button
                    type="button"
                    variant="destructive"
                    size="icon"
                    className="absolute top-2 right-2 h-6 w-6"
                    onClick={() => setImages(images.filter((_, i) => i !== idx))}
                  >
                    <X className="h-3 w-3" />
                  </Button>
                </div>
              ))}
            </div>
            <div className="border-2 border-dashed border-border rounded-lg p-6 text-center">
              <Upload className="h-8 w-8 mx-auto text-muted-foreground mb-2" />
              <Button type="button" variant="outline" size="sm">
                Ajouter des photos
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Actions */}
        <div className="flex items-center justify-end gap-4">
          <Button type="button" variant="outline" asChild>
            <Link href={`/agent/biens/${property.id}`}>Annuler</Link>
          </Button>
          <Button type="submit">
            <Save className="mr-2 h-4 w-4" />
            Enregistrer les modifications
          </Button>
        </div>
      </form>
    </div>
  )
}
