// app/connexion/page.tsx
"use client"

import { useState, Suspense } from "react"
import Link from "next/link"
import { useRouter, useSearchParams } from "next/navigation"
import { Building2, Mail, Lock, Eye, EyeOff } from "lucide-react"
import { useAuth } from "@/hooks/use-auth"
import { backendAPI } from "@/lib/backend-api"

function LoginForm() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { login } = useAuth()
  const [showPassword, setShowPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  })
  const [error, setError] = useState("")

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")
    setIsLoading(true)

    try {
      const response = await backendAPI.post("/login", formData)
      const { token, user } = response.data.data

      login(token, user)
      const redirectUrl = searchParams.get("redirect") || (user.role === 'admin' ? '/admin' : user.role === 'agent' ? '/agent' : '/client');
      router.push(redirectUrl);
    } catch (err: any) {
      setError(err.message || "Une erreur est survenue lors de la connexion.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex">
      {/* Left Side - Form */}
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="w-full max-w-md">
          <Link href="/" className="inline-flex items-center gap-2 mb-8">
            <Building2 className="h-8 w-8 text-primary" />
            <span className="text-xl font-bold text-foreground">ImmoGestion</span>
          </Link>

          <h1 className="text-2xl font-bold text-foreground mb-2">Connexion</h1>
          <p className="text-muted-foreground mb-8">
            Connectez-vous pour acceder a votre espace
          </p>

          {error && (
            <div className="mb-6 p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive text-sm">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                Adresse email
              </label>
              <div className="relative">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type="email"
                  id="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="votre@email.com"
                  className="w-full pl-10 pr-4 py-3 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-foreground mb-2">
                Mot de passe
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type={showPassword ? "text" : "password"}
                  id="password"
                  required
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="Votre mot de passe"
                  className="w-full pl-10 pr-12 py-3 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  aria-label={showPassword ? "Masquer le mot de passe" : "Afficher le mot de passe"}
                >
                  {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  className="w-4 h-4 rounded border-input text-primary focus:ring-ring"
                />
                <span className="text-sm text-muted-foreground">Se souvenir de moi</span>
              </label>
              <Link
                href="/mot-de-passe-oublie"
                className="text-sm text-primary hover:text-primary/80"
              >
                Mot de passe oublie ?
              </Link>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-3 bg-primary text-primary-foreground rounded-lg font-semibold hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? "Connexion en cours..." : "Se connecter"}
            </button>
          </form>

          <p className="mt-8 text-center text-muted-foreground">
            Pas encore de compte ?{" "}
            <Link href="/inscription" className="text-primary hover:text-primary/80 font-medium">
              Creer un compte
            </Link>
          </p>

          {/* Demo Info */}
          <div className="mt-8 p-4 bg-muted rounded-lg">
            <p className="text-sm text-muted-foreground text-center">
              <strong>Demo :</strong> Utilisez un email contenant &quot;admin&quot;, &quot;agent&quot; ou autre pour acceder aux differents espaces.
            </p>
          </div>
        </div>
      </div>

      {/* Right Side - Image */}
      <div className="hidden lg:block lg:w-1/2 bg-gradient-to-br from-sidebar to-sidebar/90 relative">
        <div className="absolute inset-0 flex items-center justify-center p-12">
          <div className="text-center text-sidebar-foreground">
            <Building2 className="h-20 w-20 mx-auto mb-6 text-sidebar-primary" />
            <h2 className="text-3xl font-bold mb-4">Bienvenue sur ImmoGestion</h2>
            <p className="text-sidebar-foreground/80 max-w-md">
              La plateforme complete pour gerer vos locations immobilieres. 
              Simple, efficace et securisee.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center bg-background text-foreground">Chargement...</div>}>
      <LoginForm />
    </Suspense>
  )
}

// frontend-vue/src/app/connexion/page.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Building2, Mail, Lock, Eye, EyeOff, ArrowRight } from 'lucide-vue-next'
import { loginUser } from '@/lib/api'
import { getUserRole } from '@/lib/session'

const router = useRouter()
const route  = useRoute()

const showPassword = ref(false)
const isLoading    = ref(false)
const error        = ref('')
const form = reactive({ email: '', password: '' })

const handleSubmit = async () => {
  error.value     = ''
  isLoading.value = true
  try {
    const result = await loginUser(form.email, form.password)
    const user   = result.user as Record<string, unknown>
    const role   = getUserRole(user) ?? (user?.role as string) ?? 'client'
    const redirect = typeof route.query.redirect === 'string' ? route.query.redirect : ''

    // Redirect URL seulement si compatible avec le rôle
    if (redirect.startsWith('/')) {
      const isClientPath = redirect.startsWith('/client')
      const isAgentPath  = redirect.startsWith('/agent')
      const isAdminPath  = redirect.startsWith('/admin')
      const canAccess =
        (isClientPath && role === 'client') ||
        (isAgentPath  && (role === 'agent' || role === 'admin')) ||
        (isAdminPath  && role === 'admin') ||
        (!isClientPath && !isAgentPath && !isAdminPath)
      if (canAccess) {
        await router.push(redirect)
        return
      }
    }

    if (role === 'admin')      await router.push('/admin')
    else if (role === 'agent') await router.push('/agent')
    else                       await router.push('/client')

  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Email ou mot de passe incorrect.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen flex bg-slate-50 antialiased text-slate-900">

    <div class="hidden lg:flex lg:w-1/2 bg-[#0f172a] relative overflow-hidden">
      <div class="absolute -top-24 -right-24 w-96 h-96 bg-sky-500 opacity-20 blur-[120px] rounded-full" />
      <div class="absolute bottom-0 left-0 w-full h-1/2 bg-gradient-to-t from-sky-500/10 to-transparent" />
      <div class="relative z-10 flex flex-col justify-center p-16 w-full">
        <div class="inline-flex p-3 bg-white/10 backdrop-blur-md rounded-2xl mb-8 w-fit border border-white/10">
          <Building2 class="h-10 w-10 text-sky-400" />
        </div>
        <h2 class="text-5xl font-extrabold text-white mb-4 leading-tight">
          ImmoGestion<br /><span class="text-sky-400">Premium.</span>
        </h2>
        <p class="text-slate-400 text-lg max-w-sm leading-relaxed">
          La plateforme complète pour gérer vos locations immobilières.
        </p>
        <div class="mt-10 space-y-4">
          <div v-for="text in [
            'Gestion des biens en temps réel',
            'Réservations avec notifications',
            'Suivi des réclamations clients'
          ]" :key="text" class="flex items-center gap-3 text-slate-300">
            <div class="flex h-6 w-6 items-center justify-center rounded-full bg-sky-500/20 text-sky-400 text-xs font-bold">✓</div>
            {{ text }}
          </div>
        </div>
      </div>
    </div>

    <div class="flex flex-1 flex-col justify-center items-center py-12 px-6">
      <div class="w-full max-w-md">

        <div class="lg:hidden flex justify-center mb-8">
          <div class="flex items-center gap-2">
            <Building2 class="h-8 w-8 text-sky-500" />
            <span class="text-2xl font-bold text-slate-950">ImmoGestion</span>
          </div>
        </div>

        <div class="bg-white rounded-[2rem] shadow-2xl shadow-slate-200 border border-slate-100 overflow-hidden">
          <div class="p-8 lg:p-10">
            <h1 class="text-2xl font-black text-slate-950">Connexion</h1>
            <p class="text-slate-500 text-sm mt-1">Ravi de vous revoir !</p>

            <div v-if="error"
              class="mt-5 p-4 bg-red-50 border-l-4 border-red-500 text-red-700 text-sm rounded-r-lg font-medium">
              {{ error }}
            </div>

            <form @submit.prevent="handleSubmit" class="mt-6 space-y-5">
              <div class="space-y-1.5">
                <label class="text-xs font-bold uppercase tracking-wider text-slate-500">Adresse email</label>
                <div class="relative group">
                  <Mail class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 group-focus-within:text-sky-500 transition-colors" />
                  <input v-model="form.email" type="email" required autocomplete="email"
                    placeholder="votre@email.com"
                    class="w-full pl-12 pr-4 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-slate-900 transition-all focus:bg-white focus:ring-4 focus:ring-sky-50 focus:border-sky-500 outline-none" />
                </div>
              </div>

              <div class="space-y-1.5">
                <label class="text-xs font-bold uppercase tracking-wider text-slate-500">Mot de passe</label>
                <div class="relative group">
                  <Lock class="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 group-focus-within:text-sky-500 transition-colors" />
                  <input v-model="form.password" :type="showPassword ? 'text' : 'password'"
                    required autocomplete="current-password" placeholder="••••••••"
                    class="w-full pl-12 pr-12 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-slate-900 transition-all focus:bg-white focus:ring-4 focus:ring-sky-50 focus:border-sky-500 outline-none" />
                  <button type="button" @click="showPassword = !showPassword"
                    class="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-700">
                    <EyeOff v-if="showPassword" class="h-5 w-5" />
                    <Eye v-else class="h-5 w-5" />
                  </button>
                </div>
              </div>

              <div class="flex items-center justify-between">
                <label class="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" class="w-4 h-4 rounded border-slate-300 text-sky-500" />
                  <span class="text-sm text-slate-500">Se souvenir</span>
                </label>
                <RouterLink to="/mot-de-passe-oublie"
                  class="text-sm font-semibold text-sky-500 hover:text-sky-600">
                  Mot de passe oublié ?
                </RouterLink>
              </div>

              <button type="submit" :disabled="isLoading"
                class="w-full py-4 bg-sky-500 text-white rounded-2xl font-bold text-lg hover:bg-sky-600 active:scale-[0.98] transition-all shadow-xl shadow-sky-200/60 flex items-center justify-center gap-3 disabled:opacity-70">
                <span v-if="isLoading" class="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                <template v-else>Se connecter <ArrowRight class="h-5 w-5" /></template>
              </button>
            </form>
          </div>

          <div class="bg-slate-50 px-8 py-4 border-t border-slate-100 text-center">
            <p class="text-sm text-slate-500">
              Pas encore de compte ?
              <RouterLink to="/inscription"
                class="ml-1 font-bold text-sky-500 hover:underline underline-offset-4">
                Créer un compte
              </RouterLink>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
