// components/dashboard-header.tsx
"use client"

import { Bell, Search } from "lucide-react"
import { useState } from "react"

interface DashboardHeaderProps {
  title: string
  subtitle?: string
}

export function DashboardHeader({ title, subtitle }: DashboardHeaderProps) {
  const [showNotifications, setShowNotifications] = useState(false)

  const notifications = [
    { id: 1, message: "Nouvelle reservation recue", time: "Il y a 5 min", unread: true },
    { id: 2, message: "Votre reclamation a ete traitee", time: "Il y a 2h", unread: true },
    { id: 3, message: "Paiement confirme", time: "Hier", unread: false },
  ]

  const unreadCount = notifications.filter(n => n.unread).length

  return (
    <header className="bg-card border-b border-border px-6 py-4">
      <div className="flex items-center justify-between gap-4">
        <div className="min-w-0 flex-1">
          <h1 className="text-xl lg:text-2xl font-bold text-foreground truncate">{title}</h1>
          {subtitle && <p className="text-sm text-muted-foreground mt-0.5">{subtitle}</p>}
        </div>

        <div className="flex items-center gap-4">
          {/* Search - Hidden on mobile */}
          <div className="hidden md:block relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <input
              type="text"
              placeholder="Rechercher..."
              className="w-64 pl-9 pr-4 py-2 bg-background border border-input rounded-lg text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>

          {/* Notifications */}
          <div className="relative">
            <button
              onClick={() => setShowNotifications(!showNotifications)}
              className="relative p-2 rounded-lg hover:bg-muted transition-colors"
              aria-label="Notifications"
            >
              <Bell className="h-5 w-5 text-muted-foreground" />
              {unreadCount > 0 && (
                <span className="absolute top-1 right-1 w-4 h-4 bg-primary text-primary-foreground text-xs rounded-full flex items-center justify-center">
                  {unreadCount}
                </span>
              )}
            </button>

            {showNotifications && (
              <>
                <div
                  className="fixed inset-0 z-40"
                  onClick={() => setShowNotifications(false)}
                />
                <div className="absolute right-0 top-full mt-2 w-80 bg-card border border-border rounded-xl shadow-lg z-50 overflow-hidden">
                  <div className="px-4 py-3 border-b border-border">
                    <h3 className="font-semibold text-foreground">Notifications</h3>
                  </div>
                  <div className="max-h-80 overflow-y-auto">
                    {notifications.map((notification) => (
                      <div
                        key={notification.id}
                        className={`px-4 py-3 border-b border-border last:border-0 hover:bg-muted/50 transition-colors ${
                          notification.unread ? "bg-muted/30" : ""
                        }`}
                      >
                        <p className="text-sm text-foreground">{notification.message}</p>
                        <p className="text-xs text-muted-foreground mt-1">{notification.time}</p>
                      </div>
                    ))}
                  </div>
                  <div className="px-4 py-3 border-t border-border text-center">
                    <button className="text-sm text-primary hover:text-primary/80">
                      Voir toutes les notifications
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    </header>
  )
}

// frontend-vue/src/components/DashboardHeader.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Bell, Search } from 'lucide-vue-next'

const props = defineProps<{ title?: string; subtitle?: string }>()
const showNotifications = ref(false)

const notifications = [
  { id: 1, message: 'Nouvelle reservation recue', time: 'Il y a 5 min', unread: true },
  { id: 2, message: 'Votre reclamation a ete traitee', time: 'Il y a 2h', unread: true },
  { id: 3, message: 'Paiement confirme', time: 'Hier', unread: false },
]

const unreadCount = computed(() => notifications.filter((item) => item.unread).length)
</script>

<template>
  <header class="border-b border-slate-200/80 bg-white/90 px-6 py-4 backdrop-blur">
    <div class="flex items-center justify-between gap-4">
      <div class="min-w-0 flex-1">
        <h1 class="truncate text-xl font-bold text-foreground lg:text-2xl">{{ title || 'Tableau de bord' }}</h1>
        <p v-if="subtitle" class="mt-0.5 text-sm text-muted-foreground">{{ subtitle }}</p>
      </div>

      <div class="flex items-center gap-4">
        <div class="relative hidden md:block">
          <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <input type="text" placeholder="Rechercher..." class="app-input w-64 py-2 pl-9 pr-4 text-sm" />
        </div>

        <div class="relative">
          <button class="relative rounded-full border border-slate-200 bg-white p-2.5 transition-colors hover:border-sky-300 hover:bg-sky-50" aria-label="Notifications" @click="showNotifications = !showNotifications">
            <Bell class="h-5 w-5 text-muted-foreground" />
            <span v-if="unreadCount > 0" class="absolute right-1 top-1 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-xs text-primary-foreground">
              {{ unreadCount }}
            </span>
          </button>

          <div v-if="showNotifications" class="fixed inset-0 z-40" @click="showNotifications = false" />

          <div v-if="showNotifications" class="absolute right-0 top-full z-50 mt-2 w-80 overflow-hidden rounded-[1.25rem] border border-slate-200 bg-white shadow-[0_22px_55px_rgba(15,23,42,0.12)]">
            <div class="border-b border-border px-4 py-3">
              <h3 class="font-semibold text-foreground">Notifications</h3>
            </div>
            <div class="max-h-80 overflow-y-auto">
              <div
                v-for="notification in notifications"
                :key="notification.id"
                :class="[
                  'border-b border-border px-4 py-3 transition-colors hover:bg-muted/50 last:border-0',
                  notification.unread ? 'bg-muted/30' : '',
                ]"
              >
                <p class="text-sm text-foreground">{{ notification.message }}</p>
                <p class="mt-1 text-xs text-muted-foreground">{{ notification.time }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>
