// app/agent/options/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { 
  Plus, 
  Search, 
  Edit, 
  Trash2,
  Wifi,
  Car,
  Waves,
  Wind,
  Tv,
  UtensilsCrossed,
  Settings
} from "lucide-react"
import { mockOptions } from "@/lib/mock-data"

const iconOptions = [
  { value: "wifi", label: "WiFi", icon: Wifi },
  { value: "car", label: "Parking", icon: Car },
  { value: "waves", label: "Piscine", icon: Waves },
  { value: "wind", label: "Climatisation", icon: Wind },
  { value: "tv", label: "Télévision", icon: Tv },
  { value: "utensils", label: "Cuisine", icon: UtensilsCrossed },
]

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  wifi: Wifi,
  car: Car,
  waves: Waves,
  wind: Wind,
  tv: Tv,
  utensils: UtensilsCrossed,
}

export default function OptionsPage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [selectedOption, setSelectedOption] = useState<typeof mockOptions[0] | null>(null)

  const filteredOptions = mockOptions.filter(option =>
    option.name.toLowerCase().includes(searchTerm.toLowerCase())
  )

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Gestion des options</h1>
          <p className="text-muted-foreground mt-1">
            Gérez les équipements et options des biens
          </p>
        </div>
        <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Ajouter une option
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Nouvelle option</DialogTitle>
              <DialogDescription>
                Créez une nouvelle option pour les biens immobiliers
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="name">Nom de l&apos;option</Label>
                <Input id="name" placeholder="Ex: Piscine chauffée" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="icon">Icône</Label>
                <Select>
                  <SelectTrigger id="icon">
                    <SelectValue placeholder="Choisir une icône" />
                  </SelectTrigger>
                  <SelectContent>
                    {iconOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        <div className="flex items-center gap-2">
                          <option.icon className="h-4 w-4" />
                          {option.label}
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="description">Description (optionnel)</Label>
                <Input id="description" placeholder="Description de l'option" />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                Annuler
              </Button>
              <Button onClick={() => setIsAddDialogOpen(false)}>
                Créer l&apos;option
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Recherche */}
      <Card>
        <CardContent className="pt-6">
          <div className="relative max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Rechercher une option..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
        </CardContent>
      </Card>

      {/* Liste des options */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {filteredOptions.map((option) => {
          const Icon = iconMap[option.icon] || Settings
          return (
            <Card key={option.id} className="hover:shadow-md transition-shadow">
              <CardContent className="pt-6">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <h3 className="font-semibold">{option.name}</h3>
                      <p className="text-sm text-muted-foreground">
                        {option.description || "Aucune description"}
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex items-center justify-between mt-4 pt-4 border-t">
                  <Badge variant="secondary">
                    Utilisé dans {Math.floor(Math.random() * 10) + 1} biens
                  </Badge>
                  <div className="flex items-center gap-1">
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="h-8 w-8"
                      onClick={() => {
                        setSelectedOption(option)
                        setIsEditDialogOpen(true)
                      }}
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {filteredOptions.length === 0 && (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Settings className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium">Aucune option trouvée</h3>
            <p className="text-muted-foreground text-center mt-1">
              Modifiez votre recherche ou créez une nouvelle option
            </p>
          </CardContent>
        </Card>
      )}

      {/* Dialog de modification */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Modifier l&apos;option</DialogTitle>
            <DialogDescription>
              Modifiez les informations de cette option
            </DialogDescription>
          </DialogHeader>
          {selectedOption && (
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="edit-name">Nom de l&apos;option</Label>
                <Input id="edit-name" defaultValue={selectedOption.name} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-icon">Icône</Label>
                <Select defaultValue={selectedOption.icon}>
                  <SelectTrigger id="edit-icon">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {iconOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        <div className="flex items-center gap-2">
                          <option.icon className="h-4 w-4" />
                          {option.label}
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-description">Description</Label>
                <Input 
                  id="edit-description" 
                  defaultValue={selectedOption.description || ""} 
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
              Annuler
            </Button>
            <Button onClick={() => setIsEditDialogOpen(false)}>
              Enregistrer
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend-vue/src/app/admin/options/page.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import {
  Plus, Search, Edit2, Trash2, Save, X, Wifi, Car, Waves,
  Wind, Trees, Droplet, Sparkles, CheckCircle2, AlertCircle
} from 'lucide-vue-next'
import { getList } from '@/lib/api'
import { getStoredToken } from '@/lib/session'

const API_BASE = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api'

const options   = ref<any[]>([])
const loading   = ref(true)
const searchTerm = ref('')
const showForm   = ref(false)
const editingId  = ref<string | null>(null)
const saving     = ref(false)
const deleting   = ref<string | null>(null)
const toast      = ref<{ msg: string; type: 'ok' | 'err' } | null>(null)

const form = reactive({ name: '', icon: '', description: '' })

const iconOptions = [
  { value: 'wifi',    label: 'Wi-Fi',         icon: Wifi },
  { value: 'waves',   label: 'Piscine',        icon: Waves },
  { value: 'car',     label: 'Parking',        icon: Car },
  { value: 'wind',    label: 'Climatisation',  icon: Wind },
  { value: 'trees',   label: 'Jardin',         icon: Trees },
  { value: 'droplet', label: 'Spa',            icon: Droplet },
  { value: 'sparkles',label: 'Autre',          icon: Sparkles },
]

const iconMap: Record<string, any> = Object.fromEntries(iconOptions.map(o => [o.value, o.icon]))
const getIcon = (v: string) => iconMap[v?.toLowerCase()] ?? Sparkles

const filtered = computed(() =>
  options.value.filter(o => o.name?.toLowerCase().includes(searchTerm.value.toLowerCase()))
)

const showToast = (msg: string, type: 'ok' | 'err') => {
  toast.value = { msg, type }
  setTimeout(() => { toast.value = null }, 3500)
}

const authHeaders = () => ({
  'Content-Type': 'application/json',
  Authorization: `Bearer ${getStoredToken()}`,
})

const load = async () => {
  loading.value = true
  try { options.value = await getList('/options') } catch { options.value = [] }
  finally { loading.value = false }
}

const openCreate = () => {
  editingId.value = null
  form.name = ''; form.icon = 'sparkles'; form.description = ''
  showForm.value = true
}

const openEdit = (opt: any) => {
  editingId.value = String(opt.id)
  form.name = opt.name ?? ''
  form.icon = opt.icon ?? 'sparkles'
  form.description = opt.description ?? ''
  showForm.value = true
}

const cancelForm = () => { showForm.value = false; editingId.value = null }

const saveOption = async () => {
  if (!form.name.trim()) { showToast('Le nom est requis', 'err'); return }
  saving.value = true
  try {
    const url    = editingId.value ? `${API_BASE}/options/${editingId.value}` : `${API_BASE}/options`
    const method = editingId.value ? 'PUT' : 'POST'
    const res    = await fetch(url, { method, headers: authHeaders(), body: JSON.stringify({ name: form.name.trim(), icon: form.icon, description: form.description }) })
    const json   = await res.json()
    if (!res.ok) throw new Error(json.message ?? 'Erreur')
    const saved = json.data
    if (editingId.value) {
      const idx = options.value.findIndex(o => String(o.id) === editingId.value)
      if (idx !== -1) options.value[idx] = saved
    } else {
      options.value.unshift(saved)
    }
    showToast(editingId.value ? 'Option modifiée ✅' : 'Option créée ✅', 'ok')
    cancelForm()
  } catch (err) {
    showToast(err instanceof Error ? err.message : 'Erreur', 'err')
  } finally { saving.value = false }
}

const deleteOption = async (id: string) => {
  if (!confirm('Supprimer cette option ?')) return
  deleting.value = id
  try {
    const res = await fetch(`${API_BASE}/options/${id}`, { method: 'DELETE', headers: authHeaders() })
    if (!res.ok) throw new Error('Erreur lors de la suppression')
    options.value = options.value.filter(o => String(o.id) !== id)
    showToast('Option supprimée', 'ok')
  } catch (err) {
    showToast(err instanceof Error ? err.message : 'Erreur', 'err')
  } finally { deleting.value = null }
}

onMounted(load)
</script>

<template>
  <div class="space-y-6 p-6">

    <!-- Toast -->
    <transition name="fade">
      <div v-if="toast" class="fixed right-6 top-6 z-50 flex items-center gap-3 rounded-2xl border px-5 py-3 shadow-xl font-semibold text-sm"
        :class="toast.type === 'ok' ? 'bg-emerald-50 border-emerald-200 text-emerald-800' : 'bg-red-50 border-red-200 text-red-800'">
        <CheckCircle2 v-if="toast.type === 'ok'" class="h-5 w-5" />
        <AlertCircle v-else class="h-5 w-5" />
        {{ toast.msg }}
      </div>
    </transition>

    <!-- Header -->
    <div class="flex flex-wrap items-start justify-between gap-4">
      <div>
        <h1 class="text-3xl font-black text-foreground">Gestion des options</h1>
        <p class="mt-1 text-muted-foreground">Créez et gérez les équipements des biens (Wi-Fi, Piscine...)</p>
      </div>
      <button @click="openCreate"
        class="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 font-bold text-primary-foreground hover:bg-primary/90 transition-colors shadow-sm">
        <Plus class="h-5 w-5" />Ajouter une option
      </button>
    </div>

    <!-- Formulaire modal -->
    <transition name="fade">
      <div v-if="showForm" class="fixed inset-0 z-40 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        <div class="w-full max-w-md rounded-2xl bg-card border border-border shadow-2xl overflow-hidden">
          <div class="flex items-center justify-between border-b border-border p-5">
            <h2 class="font-bold text-foreground text-lg">{{ editingId ? 'Modifier' : 'Nouvelle' }} option</h2>
            <button @click="cancelForm" class="rounded-full p-1 hover:bg-muted transition-colors"><X class="h-5 w-5" /></button>
          </div>
          <div class="p-5 space-y-4">
            <div>
              <label class="mb-1.5 block text-sm font-semibold text-foreground">Nom de l'option *</label>
              <input v-model="form.name" placeholder="Ex: Piscine, Wi-Fi, Parking..."
                class="w-full rounded-xl border border-input bg-background px-4 py-2.5 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20" />
            </div>
            <div>
              <label class="mb-1.5 block text-sm font-semibold text-foreground">Icône</label>
              <div class="grid grid-cols-4 gap-2">
                <button v-for="opt in iconOptions" :key="opt.value" type="button"
                  @click="form.icon = opt.value"
                  class="flex flex-col items-center gap-1 rounded-xl border-2 p-2.5 text-xs font-medium transition-all"
                  :class="form.icon === opt.value ? 'border-primary bg-primary/10 text-primary' : 'border-input hover:border-primary/50'">
                  <component :is="opt.icon" class="h-5 w-5" />
                  <span class="text-[10px]">{{ opt.label }}</span>
                </button>
              </div>
            </div>
            <div>
              <label class="mb-1.5 block text-sm font-semibold text-foreground">Description (optionnel)</label>
              <textarea v-model="form.description" rows="2" placeholder="Description courte..."
                class="w-full resize-none rounded-xl border border-input bg-background px-4 py-2.5 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20" />
            </div>
          </div>
          <div class="flex gap-3 border-t border-border p-5">
            <button @click="cancelForm" class="flex-1 rounded-xl border border-input py-2.5 text-sm font-semibold hover:bg-muted transition-colors">Annuler</button>
            <button @click="saveOption" :disabled="saving"
              class="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary py-2.5 text-sm font-bold text-primary-foreground hover:bg-primary/90 disabled:opacity-50 transition-colors">
              <Save class="h-4 w-4" />{{ saving ? 'Sauvegarde...' : 'Enregistrer' }}
            </button>
          </div>
        </div>
      </div>
    </transition>

    <!-- Search -->
    <div class="relative max-w-sm">
      <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
      <input v-model="searchTerm" placeholder="Rechercher une option..."
        class="w-full rounded-xl border border-input bg-card pl-10 pr-4 py-2.5 text-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20" />
    </div>

    <!-- Liste -->
    <div v-if="loading" class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
      <div v-for="i in 8" :key="i" class="h-24 animate-pulse rounded-2xl bg-muted" />
    </div>

    <div v-else-if="filtered.length === 0" class="flex flex-col items-center py-16 text-center">
      <Sparkles class="mb-3 h-12 w-12 text-muted-foreground" />
      <p class="font-semibold text-muted-foreground">Aucune option trouvée</p>
      <button @click="openCreate" class="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground hover:bg-primary/90 transition-colors">
        <Plus class="h-4 w-4" />Créer la première option
      </button>
    </div>

    <div v-else class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
      <div v-for="opt in filtered" :key="opt.id"
        class="group relative rounded-2xl border border-border bg-card p-5 shadow-sm hover:shadow-md hover:border-primary/30 transition-all">
        <div class="flex flex-col items-center gap-3 text-center">
          <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 group-hover:bg-primary/20 transition-colors">
            <component :is="getIcon(opt.icon)" class="h-7 w-7 text-primary" />
          </div>
          <div>
            <p class="font-bold text-foreground">{{ opt.name }}</p>
            <p v-if="opt.description" class="mt-0.5 text-xs text-muted-foreground line-clamp-1">{{ opt.description }}</p>
          </div>
        </div>
        <div class="mt-4 flex gap-2">
          <button @click="openEdit(opt)"
            class="flex flex-1 items-center justify-center gap-1 rounded-lg border border-input py-1.5 text-xs font-medium hover:bg-muted transition-colors">
            <Edit2 class="h-3.5 w-3.5" />Modifier
          </button>
          <button @click="deleteOption(String(opt.id))" :disabled="deleting === String(opt.id)"
            class="flex flex-1 items-center justify-center gap-1 rounded-lg bg-red-50 border border-red-200 py-1.5 text-xs font-medium text-red-600 hover:bg-red-100 disabled:opacity-50 transition-colors">
            <Trash2 class="h-3.5 w-3.5" />Supprimer
          </button>
        </div>
      </div>
    </div>

  </div>
</template>

<style scoped>
.fade-enter-active, .fade-leave-active { transition: opacity 0.2s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
