// app/admin/roles/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { 
  Plus, 
  Edit, 
  Trash2,
  Shield,
  Users,
  Settings
} from "lucide-react"

const mockRoles = [
  {
    id: "1",
    name: "Administrateur",
    description: "Accès complet à toutes les fonctionnalités",
    usersCount: 2,
    permissions: ["all"],
    isSystem: true
  },
  {
    id: "2",
    name: "Agent",
    description: "Gestion des biens, réservations et réclamations",
    usersCount: 5,
    permissions: ["biens.view", "biens.edit", "reservations.view", "reservations.edit", "reclamations.view", "reclamations.edit", "clients.view"],
    isSystem: true
  },
  {
    id: "3",
    name: "Superviseur",
    description: "Accès en lecture seule aux statistiques",
    usersCount: 1,
    permissions: ["stats.view", "biens.view", "reservations.view"],
    isSystem: false
  },
]

export default function RolesPage() {
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [selectedRole, setSelectedRole] = useState<typeof mockRoles[0] | null>(null)

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Gestion des rôles</h1>
          <p className="text-muted-foreground mt-1">
            Configurez les rôles et niveaux d&apos;accès
          </p>
        </div>
        <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Créer un rôle
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Nouveau rôle</DialogTitle>
              <DialogDescription>
                Créez un nouveau rôle avec des permissions personnalisées
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="roleName">Nom du rôle *</Label>
                <Input id="roleName" placeholder="Ex: Superviseur" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="roleDescription">Description</Label>
                <Textarea 
                  id="roleDescription" 
                  placeholder="Décrivez les responsabilités de ce rôle..."
                  rows={3}
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                Annuler
              </Button>
              <Button onClick={() => setIsAddDialogOpen(false)}>
                Créer le rôle
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Liste des rôles */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {mockRoles.map((role) => (
          <Card key={role.id} className="relative">
            {role.isSystem && (
              <Badge variant="secondary" className="absolute top-4 right-4">
                Système
              </Badge>
            )}
            <CardHeader>
              <div className="flex items-center gap-3">
                <div className={`w-12 h-12 rounded-lg flex items-center justify-center ${
                  role.name === "Administrateur" ? "bg-primary/10" :
                  role.name === "Agent" ? "bg-green-100" : "bg-orange-100"
                }`}>
                  <Shield className={`h-6 w-6 ${
                    role.name === "Administrateur" ? "text-primary" :
                    role.name === "Agent" ? "text-green-600" : "text-orange-600"
                  }`} />
                </div>
                <div>
                  <CardTitle className="text-lg">{role.name}</CardTitle>
                  <CardDescription>{role.description}</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-2 mb-4">
                <Users className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm text-muted-foreground">
                  {role.usersCount} utilisateur(s)
                </span>
              </div>

              <div className="flex flex-wrap gap-2 mb-4">
                {role.permissions.slice(0, 3).map((perm) => (
                  <Badge key={perm} variant="outline" className="text-xs">
                    {perm === "all" ? "Toutes" : perm.split('.')[0]}
                  </Badge>
                ))}
                {role.permissions.length > 3 && (
                  <Badge variant="outline" className="text-xs">
                    +{role.permissions.length - 3}
                  </Badge>
                )}
              </div>

              <div className="flex items-center gap-2 pt-4 border-t">
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="flex-1"
                  onClick={() => {
                    setSelectedRole(role)
                    setIsEditDialogOpen(true)
                  }}
                >
                  <Edit className="mr-2 h-4 w-4" />
                  Modifier
                </Button>
                {!role.isSystem && (
                  <Button variant="outline" size="sm" className="text-destructive hover:text-destructive">
                    <Trash2 className="h-4 w-4" />
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Dialog de modification */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Modifier le rôle</DialogTitle>
            <DialogDescription>
              Modifiez les informations et permissions de ce rôle
            </DialogDescription>
          </DialogHeader>
          {selectedRole && (
            <div className="space-y-4 py-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="editRoleName">Nom du rôle</Label>
                  <Input 
                    id="editRoleName" 
                    defaultValue={selectedRole.name}
                    disabled={selectedRole.isSystem}
                  />
                </div>
                <div className="space-y-2">
                  <Label>Utilisateurs</Label>
                  <Input value={`${selectedRole.usersCount} utilisateur(s)`} disabled />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="editRoleDescription">Description</Label>
                <Textarea 
                  id="editRoleDescription" 
                  defaultValue={selectedRole.description}
                  rows={2}
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
              Annuler
            </Button>
            <Button onClick={() => setIsEditDialogOpen(false)}>
              Enregistrer
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend-vue/src/app/admin/roles/page.vue
<template>
  <div class="space-y-6 p-6">
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
      <div>
        <h1 class="text-3xl font-bold text-slate-900">Gestion des rôles</h1>
        <p class="text-slate-500 mt-1">Configurez les rôles et niveaux d'accès</p>
      </div>
      <button 
        @click="openAddDialog"
        class="inline-flex items-center justify-center px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-all shadow-sm"
      >
        <Plus class="mr-2 h-4 w-4" />
        Créer un rôle
      </button>
    </div>

    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <div 
        v-for="role in roles" 
        :key="role.id" 
        class="bg-white rounded-xl border border-slate-200 shadow-sm relative hover:shadow-md transition-shadow flex flex-col"
      >
        <span 
          v-if="role.isSystem" 
          class="absolute top-4 right-4 px-2 py-1 bg-slate-100 text-slate-600 text-[10px] font-bold uppercase rounded-md border border-slate-200"
        >
          Système
        </span>

        <div class="p-6 flex-1">
          <div class="flex items-center gap-3 mb-4">
            <div :class="[
              'w-12 h-12 rounded-xl flex items-center justify-center shadow-sm',
              role.name === 'Administrateur' ? 'bg-blue-50 text-blue-600' :
              role.name === 'Agent' ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-600'
            ]">
              <Shield class="h-6 w-6" />
            </div>
            <div>
              <h3 class="text-lg font-bold text-slate-900">{{ role.name }}</h3>
              <p class="text-xs text-slate-500 line-clamp-1">{{ role.description }}</p>
            </div>
          </div>

          <div class="flex items-center gap-2 mb-4 text-slate-500">
            <Users class="h-4 w-4" />
            <span class="text-sm">{{ role.usersCount }} utilisateur(s)</span>
          </div>

          <div class="flex flex-wrap gap-2 mb-4">
            <span 
              v-for="perm in role.permissions.slice(0, 3)" 
              :key="perm"
              class="px-2 py-0.5 bg-slate-50 text-slate-600 border border-slate-200 rounded text-[11px] font-medium"
            >
              {{ perm === 'all' ? 'Toutes' : perm.split('.')[0] }}
            </span>
            <span 
              v-if="role.permissions.length > 3"
              class="px-2 py-0.5 bg-white text-blue-600 border border-blue-100 rounded text-[11px] font-bold"
            >
              +{{ role.permissions.length - 3 }}
            </span>
          </div>
        </div>

        <div class="px-6 py-4 border-t border-slate-100 bg-slate-50/50 rounded-b-xl flex items-center gap-2">
          <button 
            @click="openEditDialog(role)"
            class="flex-1 inline-flex items-center justify-center gap-2 px-3 py-2 text-sm font-bold text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
          >
            <Edit class="h-4 w-4" />
            Modifier
          </button>
          <button 
            v-if="!role.isSystem"
            @click="deleteRole(role.id)"
            class="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors border border-transparent hover:border-red-100"
          >
            <Trash2 class="h-4 w-4" />
          </button>
        </div>
      </div>
    </div>

    <div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
      <div class="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in duration-200">
        <div class="p-6 border-b border-slate-100">
          <h3 class="text-xl font-bold text-slate-900">
            {{ isEditing ? 'Modifier le rôle' : 'Nouveau rôle' }}
          </h3>
          <p class="text-sm text-slate-500">
            {{ isEditing ? 'Modifiez les informations de ce rôle' : 'Créez un nouveau rôle avec des permissions personnalisées' }}
          </p>
        </div>

        <div class="p-6 space-y-4">
          <div class="space-y-1">
            <label class="text-sm font-bold text-slate-700">Nom du rôle *</label>
            <input 
              v-model="formData.name" 
              type="text" 
              :disabled="formData.isSystem"
              class="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500/20 outline-none disabled:bg-slate-50 disabled:text-slate-400"
              placeholder="Ex: Superviseur"
            />
          </div>
          
          <div class="space-y-1">
            <label class="text-sm font-bold text-slate-700">Description</label>
            <textarea 
              v-model="formData.description" 
              rows="3"
              class="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500/20 outline-none resize-none"
              placeholder="Décrivez les responsabilités..."
            ></textarea>
          </div>

          <div v-if="isEditing" class="p-3 bg-blue-50 rounded-lg flex items-center gap-3">
            <Users class="h-5 w-5 text-blue-600" />
            <span class="text-sm text-blue-700 font-medium">Ce rôle est actuellement assigné à {{ formData.usersCount }} utilisateurs.</span>
          </div>
        </div>

        <div class="p-6 bg-slate-50 flex justify-end gap-3">
          <button @click="showModal = false" class="px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-200 rounded-lg transition-colors">
            Annuler
          </button>
          <button @click="saveRole" class="px-6 py-2 text-sm font-bold bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-shadow shadow-md shadow-blue-200">
            {{ isEditing ? 'Enregistrer' : 'Créer le rôle' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Plus, Edit, Trash2, Shield, Users } from 'lucide-vue-next'

// Données initiales
const roles = ref([
  {
    id: "1",
    name: "Administrateur",
    description: "Accès complet à toutes les fonctionnalités",
    usersCount: 2,
    permissions: ["all"],
    isSystem: true
  },
  {
    id: "2",
    name: "Agent",
    description: "Gestion des biens, réservations et réclamations",
    usersCount: 5,
    permissions: ["biens.view", "biens.edit", "reservations.view", "reservations.edit", "reclamations.view"],
    isSystem: true
  },
  {
    id: "3",
    name: "Superviseur",
    description: "Accès en lecture seule aux statistiques",
    usersCount: 1,
    permissions: ["stats.view", "biens.view", "reservations.view"],
    isSystem: false
  }
])

// État de la modale et du formulaire
const showModal = ref(false)
const isEditing = ref(false)
const formData = ref({
  id: "",
  name: "",
  description: "",
  isSystem: false,
  usersCount: 0
})

const openAddDialog = () => {
  isEditing.value = false
  formData.value = { id: "", name: "", description: "", isSystem: false, usersCount: 0 }
  showModal.value = true
}

const openEditDialog = (role: any) => {
  isEditing.value = true
  formData.value = { ...role }
  showModal.value = true
}

const saveRole = () => {
  if (isEditing.value) {
    const index = roles.value.findIndex(r => r.id === formData.value.id)
    if (index !== -1) roles.value[index] = { ...roles.value[index], ...formData.value }
  } else {
    roles.value.push({
      ...formData.value,
      id: Date.now().toString(),
      usersCount: 0,
      permissions: ["biens.view"] // Permission par défaut
    })
  }
  showModal.value = false
}

const deleteRole = (id: string) => {
  if (confirm("Êtes-vous sûr de vouloir supprimer ce rôle ?")) {
    roles.value = roles.value.filter(r => r.id !== id)
  }
}
</script>
