// app/agent/layout.tsx
"use client"

import { DashboardSidebar } from "@/components/dashboard-sidebar"
import { DashboardHeader } from "@/components/dashboard-header"

export default function AgentLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex min-h-screen bg-background">
      <DashboardSidebar role="agent" />
      <div className="flex-1 flex flex-col">
        <DashboardHeader />
        <main className="flex-1 p-6 overflow-auto">{children}</main>
      </div>
    </div>
  )
}

// frontend-vue/src/app/admin/layout.vue
<template>
  <div class="flex min-h-screen bg-slate-50">
    <DashboardSidebar role="admin" />

    <div class="flex-1 flex flex-col">
      <DashboardHeader />

      <main class="flex-1 p-6 overflow-auto">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
// Importation des composants de structure
import DashboardSidebar from "@/components/DashboardSidebar.vue"
import DashboardHeader from "@/components/DashboardHeader.vue"
</script>

<style scoped>
/* Ajoute ici des styles spécifiques au layout si nécessaire */
</style>
