// app/admin/permissions/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { 
  Plus, 
  Shield,
  Building2,
  CalendarCheck,
  MessageSquare,
  Users,
  Settings,
  Eye,
  Edit,
  Trash2,
  Save
} from "lucide-react"

const permissionGroups = [
  {
    name: "Biens immobiliers",
    icon: Building2,
    permissions: [
      { id: "biens.view", name: "Voir les biens", description: "Accès en lecture aux biens" },
      { id: "biens.create", name: "Créer des biens", description: "Ajouter de nouveaux biens" },
      { id: "biens.edit", name: "Modifier les biens", description: "Éditer les biens existants" },
      { id: "biens.delete", name: "Supprimer les biens", description: "Supprimer des biens" },
    ]
  },
  {
    name: "Réservations",
    icon: CalendarCheck,
    permissions: [
      { id: "reservations.view", name: "Voir les réservations", description: "Accès en lecture" },
      { id: "reservations.confirm", name: "Confirmer", description: "Confirmer les réservations" },
      { id: "reservations.reject", name: "Refuser", description: "Refuser les réservations" },
      { id: "reservations.delete", name: "Supprimer", description: "Supprimer les réservations" },
    ]
  },
  {
    name: "Réclamations",
    icon: MessageSquare,
    permissions: [
      { id: "reclamations.view", name: "Voir les réclamations", description: "Accès en lecture" },
      { id: "reclamations.respond", name: "Répondre", description: "Répondre aux réclamations" },
      { id: "reclamations.close", name: "Clôturer", description: "Fermer les réclamations" },
    ]
  },
  {
    name: "Clients",
    icon: Users,
    permissions: [
      { id: "clients.view", name: "Voir les clients", description: "Accès en lecture" },
      { id: "clients.edit", name: "Modifier", description: "Modifier les informations clients" },
      { id: "clients.delete", name: "Supprimer", description: "Supprimer des clients" },
    ]
  },
  {
    name: "Administration",
    icon: Settings,
    permissions: [
      { id: "admin.users", name: "Gérer les utilisateurs", description: "CRUD sur les agents" },
      { id: "admin.roles", name: "Gérer les rôles", description: "Configurer les rôles" },
      { id: "admin.permissions", name: "Gérer les permissions", description: "Attribuer les permissions" },
      { id: "admin.settings", name: "Paramètres système", description: "Configuration globale" },
    ]
  },
]

const roles = [
  { id: "admin", name: "Administrateur", permissions: ["all"] },
  { id: "agent", name: "Agent", permissions: ["biens.view", "biens.create", "biens.edit", "reservations.view", "reservations.confirm", "reservations.reject", "reclamations.view", "reclamations.respond", "clients.view"] },
  { id: "supervisor", name: "Superviseur", permissions: ["biens.view", "reservations.view", "reclamations.view", "clients.view"] },
]

export default function PermissionsPage() {
  const [selectedRole, setSelectedRole] = useState("agent")
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false)

  const currentRole = roles.find(r => r.id === selectedRole)
  const hasPermission = (permId: string) => {
    return currentRole?.permissions.includes("all") || currentRole?.permissions.includes(permId)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Gestion des permissions</h1>
          <p className="text-muted-foreground mt-1">
            Configurez les permissions par rôle
          </p>
        </div>
        <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Nouvelle permission
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Nouvelle permission</DialogTitle>
              <DialogDescription>
                Créez une nouvelle permission personnalisée
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="permName">Nom de la permission *</Label>
                <Input id="permName" placeholder="Ex: rapports.view" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="permLabel">Libellé</Label>
                <Input id="permLabel" placeholder="Ex: Voir les rapports" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="permDesc">Description</Label>
                <Input id="permDesc" placeholder="Description de la permission" />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                Annuler
              </Button>
              <Button onClick={() => setIsAddDialogOpen(false)}>
                Créer
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-6 lg:grid-cols-4">
        {/* Sélection du rôle */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5" />
              Rôles
            </CardTitle>
            <CardDescription>Sélectionnez un rôle à configurer</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {roles.map((role) => (
              <button
                key={role.id}
                onClick={() => setSelectedRole(role.id)}
                className={`w-full text-left p-3 rounded-lg border transition-colors ${
                  selectedRole === role.id 
                    ? "bg-primary text-primary-foreground border-primary" 
                    : "hover:bg-muted"
                }`}
              >
                <p className="font-medium">{role.name}</p>
                <p className={`text-xs ${selectedRole === role.id ? "text-primary-foreground/80" : "text-muted-foreground"}`}>
                  {role.permissions.includes("all") 
                    ? "Toutes les permissions" 
                    : `${role.permissions.length} permissions`}
                </p>
              </button>
            ))}
          </CardContent>
        </Card>

        {/* Permissions */}
        <Card className="lg:col-span-3">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Permissions - {currentRole?.name}</CardTitle>
                <CardDescription>
                  Cochez les permissions à accorder à ce rôle
                </CardDescription>
              </div>
              <Button>
                <Save className="mr-2 h-4 w-4" />
                Enregistrer
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <Accordion type="multiple" defaultValue={permissionGroups.map(g => g.name)} className="space-y-4">
              {permissionGroups.map((group) => (
                <AccordionItem key={group.name} value={group.name} className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <group.icon className="h-5 w-5 text-primary" />
                      </div>
                      <div className="text-left">
                        <p className="font-medium">{group.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {group.permissions.filter(p => hasPermission(p.id)).length}/{group.permissions.length} actives
                        </p>
                      </div>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pt-4">
                    <div className="grid gap-3 sm:grid-cols-2">
                      {group.permissions.map((permission) => (
                        <div 
                          key={permission.id}
                          className={`flex items-start gap-3 p-3 rounded-lg border ${
                            hasPermission(permission.id) ? "bg-green-50 border-green-200" : ""
                          }`}
                        >
                          <Checkbox 
                            id={permission.id}
                            checked={hasPermission(permission.id)}
                            disabled={currentRole?.permissions.includes("all")}
                          />
                          <div className="flex-1">
                            <label 
                              htmlFor={permission.id}
                              className="text-sm font-medium cursor-pointer"
                            >
                              {permission.name}
                            </label>
                            <p className="text-xs text-muted-foreground">
                              {permission.description}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// frontend-vue/src/app/admin/permissions/page.vue
<template>
  <div class="space-y-6 p-6">
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
      <div>
        <h1 class="text-3xl font-bold text-slate-900">Gestion des permissions</h1>
        <p class="text-slate-500 mt-1">Configurez les permissions par rôle</p>
      </div>
      <button 
        @click="isAddDialogOpen = true"
        class="inline-flex items-center justify-center px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors shadow-sm"
      >
        <Plus class="mr-2 h-4 w-4" />
        Nouvelle permission
      </button>
    </div>

    <div class="grid gap-6 lg:grid-cols-4">
      <aside class="lg:col-span-1 space-y-4">
        <div class="bg-white rounded-xl border border-slate-200 shadow-sm p-4">
          <div class="flex items-center gap-2 font-semibold text-slate-900 mb-4">
            <Shield class="h-5 w-5 text-blue-600" />
            Rôles
          </div>
          <div class="space-y-2">
            <button
              v-for="role in roles"
              :key="role.id"
              @click="selectedRoleId = role.id"
              :class="[
                'w-full text-left p-3 rounded-lg border transition-all',
                selectedRoleId === role.id 
                  ? 'bg-blue-600 text-white border-blue-600 shadow-md shadow-blue-200' 
                  : 'hover:bg-slate-50 border-slate-100 text-slate-700'
              ]"
            >
              <p class="font-bold">{{ role.name }}</p>
              <p :class="['text-xs', selectedRoleId === role.id ? 'text-blue-100' : 'text-slate-400']">
                {{ role.permissions.includes('all') ? 'Toutes les permissions' : `${role.permissions.length} actives` }}
              </p>
            </button>
          </div>
        </div>
      </aside>

      <main class="lg:col-span-3">
        <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div class="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/30">
            <div>
              <h2 class="text-xl font-bold text-slate-900">Permissions - {{ currentRole?.name }}</h2>
              <p class="text-sm text-slate-500">Cochez les permissions à accorder à ce rôle</p>
            </div>
            <button @click="savePermissions" class="inline-flex items-center px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-all shadow-sm">
              <Save class="mr-2 h-4 w-4" />
              Enregistrer
            </button>
          </div>

          <div class="p-6 space-y-4">
            <div v-for="group in permissionGroups" :key="group.name" class="border border-slate-200 rounded-xl overflow-hidden">
              <button 
                @click="toggleGroup(group.name)"
                class="w-full flex items-center justify-between p-4 bg-white hover:bg-slate-50 transition-colors"
              >
                <div class="flex items-center gap-3">
                  <div class="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center text-blue-600">
                    <component :is="group.icon" class="h-5 w-5" />
                  </div>
                  <div class="text-left">
                    <p class="font-bold text-slate-900">{{ group.name }}</p>
                    <p class="text-xs text-slate-500">{{ getActiveCount(group) }}/{{ group.permissions.length }} actives</p>
                  </div>
                </div>
                <ChevronDown :class="['h-5 w-5 text-slate-400 transition-transform', openedGroups.includes(group.name) ? 'rotate-180' : '']" />
              </button>

              <div v-show="openedGroups.includes(group.name)" class="p-4 bg-slate-50/50 border-t border-slate-100 grid gap-3 sm:grid-cols-2">
                <div 
                  v-for="perm in group.permissions" 
                  :key="perm.id"
                  @click="togglePermission(perm.id)"
                  :class="[
                    'flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-all',
                    hasPermission(perm.id) ? 'bg-green-50 border-green-200 shadow-sm' : 'bg-white border-slate-200 opacity-60'
                  ]"
                >
                  <div :class="['w-5 h-5 rounded border flex items-center justify-center mt-0.5 transition-colors', hasPermission(perm.id) ? 'bg-green-600 border-green-600' : 'bg-white border-slate-300']">
                    <Check v-if="hasPermission(perm.id)" class="h-3 w-3 text-white" />
                  </div>
                  <div class="flex-1">
                    <p class="text-sm font-bold text-slate-900">{{ perm.name }}</p>
                    <p class="text-xs text-slate-500 leading-tight">{{ perm.description }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>

    <div v-if="isAddDialogOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
      <div class="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden">
        <div class="p-6 border-b border-slate-100">
          <h3 class="text-lg font-bold text-slate-900">Nouvelle permission</h3>
          <p class="text-sm text-slate-500">Créez une nouvelle permission personnalisée</p>
        </div>
        <div class="p-6 space-y-4">
          <div class="space-y-1">
            <label class="text-sm font-semibold text-slate-700">Nom de la permission *</label>
            <input type="text" placeholder="Ex: rapports.view" class="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500/20 outline-none" />
          </div>
          <div class="space-y-1">
            <label class="text-sm font-semibold text-slate-700">Libellé</label>
            <input type="text" placeholder="Ex: Voir les rapports" class="w-full px-3 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500/20 outline-none" />
          </div>
        </div>
        <div class="p-6 bg-slate-50 flex justify-end gap-3">
          <button @click="isAddDialogOpen = false" class="px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-100 rounded-lg">Annuler</button>
          <button @click="isAddDialogOpen = false" class="px-4 py-2 text-sm font-bold bg-blue-600 text-white rounded-lg hover:bg-blue-700">Créer</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { 
  Plus, Shield, Building2, CalendarCheck, 
  Save, 
  ChevronDown, Check 
} from 'lucide-vue-next'

// Données des groupes (comme dans ton React)
type PermissionItem = {
  id: string
  name: string
  description: string
}

type PermissionGroup = {
  name: string
  icon: unknown
  permissions: PermissionItem[]
}

const permissionGroups: PermissionGroup[] = [
  {
    name: "Biens immobiliers",
    icon: Building2,
    permissions: [
      { id: "biens.view", name: "Voir les biens", description: "Accès en lecture aux biens" },
      { id: "biens.create", name: "Créer des biens", description: "Ajouter de nouveaux biens" },
      { id: "biens.edit", name: "Modifier les biens", description: "Éditer les biens existants" },
      { id: "biens.delete", name: "Supprimer les biens", description: "Supprimer des biens" },
    ]
  },
  {
    name: "Réservations",
    icon: CalendarCheck,
    permissions: [
      { id: "reservations.view", name: "Voir les réservations", description: "Accès en lecture" },
      { id: "reservations.confirm", name: "Confirmer", description: "Confirmer les réservations" },
      { id: "reservations.reject", name: "Refuser", description: "Refuser les réservations" },
    ]
  },
  // ... Ajoute les autres groupes ici
]

const roles = ref([
  { id: "admin", name: "Administrateur", permissions: ["all"] },
  { id: "agent", name: "Agent", permissions: ["biens.view", "biens.create", "reservations.view"] },
  { id: "supervisor", name: "Superviseur", permissions: ["biens.view", "reservations.view"] },
])

const selectedRoleId = ref("agent")
const isAddDialogOpen = ref(false)
const openedGroups = ref(["Biens immobiliers"]) // Groupes ouverts par défaut

const currentRole = computed(() => roles.value.find(r => r.id === selectedRoleId.value))

const hasPermission = (permId: string) => {
  return currentRole.value?.permissions.includes("all") || currentRole.value?.permissions.includes(permId)
}

const toggleGroup = (name: string) => {
  if (openedGroups.value.includes(name)) {
    openedGroups.value = openedGroups.value.filter(g => g !== name)
  } else {
    openedGroups.value.push(name)
  }
}

const togglePermission = (permId: string) => {
  if (!currentRole.value || currentRole.value.permissions.includes("all")) return
  
  const perms = [...currentRole.value.permissions]
  const index = perms.indexOf(permId)
  
  if (index > -1) perms.splice(index, 1)
  else perms.push(permId)
  
  currentRole.value.permissions = perms
}

const getActiveCount = (group: PermissionGroup) => {
  return group.permissions.filter(p => hasPermission(p.id)).length
}

const savePermissions = () => {
  alert(`Permissions pour ${currentRole.value?.name} enregistrées !`)
}
</script>
