// frontend-vue/src/app/agent/clients/page.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Search, Eye, Users, Mail, Phone, Calendar } from 'lucide-vue-next'
import { getList } from '@/lib/api'

const clients = ref<any[]>([])
const reservations = ref<any[]>([])

const searchTerm = ref('')

const filteredClients = computed(() => {
  const term = searchTerm.value.toLowerCase()
  return clients.value.filter((client) => {
    const fullName = `${client.first_name ?? client.firstName} ${client.last_name ?? client.lastName}`.toLowerCase()
    return (
      fullName.includes(term) ||
      client.email.toLowerCase().includes(term) ||
      client.phone.includes(searchTerm.value)
    )
  })
})

const getClientReservationsCount = (clientId: string) =>
  reservations.value.filter((reservation) => String(reservation.client_id || reservation.clientId) === String(clientId)).length

onMounted(async () => {
  clients.value = await getList('/clients')
  reservations.value = await getList('/reservations')
})
</script>

<template>
  <div class="space-y-6 p-6">
    <div>
      <h1 class="text-3xl font-bold text-foreground">Gestion des clients</h1>
      <p class="mt-1 text-muted-foreground">
        {{ clients.length }} clients inscrits sur la plateforme
      </p>
    </div>

    <section class="grid gap-4 sm:grid-cols-3">
      <article class="rounded-xl border border-border bg-card p-5">
        <div class="flex items-center gap-3">
          <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
            <Users class="h-6 w-6 text-primary" />
          </div>
          <div>
            <p class="text-2xl font-bold">{{ clients.length }}</p>
            <p class="text-sm text-muted-foreground">Clients total</p>
          </div>
        </div>
      </article>

      <article class="rounded-xl border border-border bg-card p-5">
        <div class="flex items-center gap-3">
          <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-green-100">
            <Calendar class="h-6 w-6 text-green-600" />
          </div>
          <div>
            <p class="text-2xl font-bold">{{ reservations.length }}</p>
            <p class="text-sm text-muted-foreground">Reservations totales</p>
          </div>
        </div>
      </article>

      <article class="rounded-xl border border-border bg-card p-5">
        <div class="flex items-center gap-3">
          <div class="flex h-12 w-12 items-center justify-center rounded-lg bg-orange-100">
            <Users class="h-6 w-6 text-orange-600" />
          </div>
          <div>
            <p class="text-2xl font-bold">
              {{ clients.filter((c) => reservations.some((r) => String(r.client_id || r.clientId) === String(c.id))).length }}
            </p>
            <p class="text-sm text-muted-foreground">Clients actifs</p>
          </div>
        </div>
      </article>
    </section>

    <div class="rounded-xl border border-border bg-card p-4">
      <div class="relative max-w-md">
        <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <input
          v-model="searchTerm"
          placeholder="Rechercher par nom, email ou telephone..."
          class="w-full rounded-lg border border-input bg-background py-2 pl-10 pr-3"
        />
      </div>
    </div>

    <div class="rounded-xl border border-border bg-card p-5">
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead>
            <tr class="border-b border-border text-left text-muted-foreground">
              <th class="px-3 py-2">Client</th>
              <th class="px-3 py-2">Contact</th>
              <th class="px-3 py-2">Inscrit le</th>
              <th class="px-3 py-2">Reservations</th>
              <th class="px-3 py-2">Statut</th>
              <th class="px-3 py-2 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="client in filteredClients"
              :key="client.id"
              class="border-b border-border/60 hover:bg-muted/40"
            >
              <td class="px-3 py-3">
                <div class="flex items-center gap-3">
                  <div class="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 text-primary">
                    {{ (client.first_name ?? client.firstName)[0] }}{{ (client.last_name ?? client.lastName)[0] }}
                  </div>
                  <p class="font-medium">{{ client.first_name ?? client.firstName }} {{ client.last_name ?? client.lastName }}</p>
                </div>
              </td>
              <td class="px-3 py-3">
                <p class="flex items-center gap-2"><Mail class="h-3 w-3 text-muted-foreground" />{{ client.email }}</p>
                <p class="flex items-center gap-2 text-muted-foreground"><Phone class="h-3 w-3" />{{ client.phone }}</p>
              </td>
              <td class="px-3 py-3">{{ new Date(client.created_at || client.createdAt).toLocaleDateString('fr-FR') }}</td>
              <td class="px-3 py-3">
                <span class="rounded bg-secondary px-2 py-1 text-xs">
                  {{ getClientReservationsCount(client.id) }} reservation(s)
                </span>
              </td>
              <td class="px-3 py-3">
                <span
                  :class="[
                    'rounded-full px-2 py-1 text-xs',
                    client.status === 'actif' ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-600',
                  ]"
                >
                  {{ client.status }}
                </span>
              </td>
              <td class="px-3 py-3 text-right">
                <RouterLink :to="`/agent/clients/${client.id}`" class="inline-flex items-center gap-2 text-primary">
                  <Eye class="h-4 w-4" />
                  Voir
                </RouterLink>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// app/agent/clients/page.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { 
  Search, 
  Eye, 
  Users,
  Mail,
  Phone,
  Calendar
} from "lucide-react"
import Link from "next/link"
import { mockClients, mockReservations } from "@/lib/mock-data"

export default function AgentClientsPage() {
  const [searchTerm, setSearchTerm] = useState("")

  const filteredClients = mockClients.filter(client => {
    const fullName = `${client.firstName} ${client.lastName}`.toLowerCase()
    return fullName.includes(searchTerm.toLowerCase()) ||
           client.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
           client.phone.includes(searchTerm)
  })

  const getClientReservationsCount = (clientId: string) => {
    return mockReservations.filter(r => r.clientId === clientId).length
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground">Gestion des clients</h1>
        <p className="text-muted-foreground mt-1">
          {mockClients.length} clients inscrits sur la plateforme
        </p>
      </div>

      {/* Stats rapides */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center">
                <Users className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{mockClients.length}</p>
                <p className="text-sm text-muted-foreground">Clients total</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-green-100 flex items-center justify-center">
                <Calendar className="h-6 w-6 text-green-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{mockReservations.length}</p>
                <p className="text-sm text-muted-foreground">Réservations totales</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-orange-100 flex items-center justify-center">
                <Users className="h-6 w-6 text-orange-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {mockClients.filter(c => mockReservations.some(r => r.clientId === c.id)).length}
                </p>
                <p className="text-sm text-muted-foreground">Clients actifs</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Recherche */}
      <Card>
        <CardContent className="pt-6">
          <div className="relative max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Rechercher par nom, email ou téléphone..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
        </CardContent>
      </Card>

      {/* Tableau des clients */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Users className="h-5 w-5" />
            Liste des clients
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Client</TableHead>
                  <TableHead>Contact</TableHead>
                  <TableHead>Inscrit le</TableHead>
                  <TableHead>Réservations</TableHead>
                  <TableHead>Statut</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredClients.map((client) => {
                  const reservationsCount = getClientReservationsCount(client.id)
                  return (
                    <TableRow key={client.id}>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          <Avatar>
                            <AvatarFallback className="bg-primary/10 text-primary">
                              {client.firstName[0]}{client.lastName[0]}
                            </AvatarFallback>
                          </Avatar>
                          <div>
                            <p className="font-medium">{client.firstName} {client.lastName}</p>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="space-y-1">
                          <div className="flex items-center gap-2 text-sm">
                            <Mail className="h-3 w-3 text-muted-foreground" />
                            <span>{client.email}</span>
                          </div>
                          <div className="flex items-center gap-2 text-sm text-muted-foreground">
                            <Phone className="h-3 w-3" />
                            <span>{client.phone}</span>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        {new Date(client.createdAt).toLocaleDateString('fr-FR')}
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary">
                          {reservationsCount} réservation(s)
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge variant={client.status === "actif" ? "default" : "outline"}>
                          {client.status === "actif" ? "Actif" : "Inactif"}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button variant="ghost" size="sm" asChild>
                          <Link href={`/agent/clients/${client.id}`}>
                            <Eye className="mr-2 h-4 w-4" />
                            Voir
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
          </div>

          {filteredClients.length === 0 && (
            <div className="text-center py-12">
              <Users className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <h3 className="text-lg font-medium">Aucun client trouvé</h3>
              <p className="text-muted-foreground">Modifiez votre recherche</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
