// frontend-vue/src/app/client/reservations/[id]/page.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowLeft, Calendar, MapPin, Clock, CheckCircle, XCircle, Ban, MessageSquare, Bed, Bath, Maximize } from 'lucide-vue-next'
import DashboardHeader from '@/components/DashboardHeader.vue'
import { getDetail } from '@/lib/api'

type ReservationStatus = 'en_attente' | 'confirmee' | 'refusee' | 'annulee'

const route = useRoute()
const reservation = ref<any | null>(null)

const statusColors: Record<ReservationStatus, string> = {
  en_attente: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  confirmee: 'bg-green-100 text-green-800 border-green-200',
  refusee: 'bg-red-100 text-red-800 border-red-200',
  annulee: 'bg-gray-100 text-gray-800 border-gray-200',
}
const statusLabels: Record<ReservationStatus, string> = {
  en_attente: 'Reservation en attente de confirmation',
  confirmee: 'Reservation confirmee',
  refusee: 'Reservation refusee',
  annulee: 'Reservation annulee',
}
const statusIcons: Record<ReservationStatus, any> = { en_attente: Clock, confirmee: CheckCircle, refusee: XCircle, annulee: Ban }

const getStatusClass = (status: string) => statusColors[status as ReservationStatus] || statusColors.en_attente
const getStatusIcon = (status: string) => statusIcons[status as ReservationStatus] || Clock
const getStatusLabel = (status: string) => statusLabels[status as ReservationStatus] || status

onMounted(async () => {
  try {
    reservation.value = await getDetail('/reservations', String(route.params.id))
  } catch {
    reservation.value = null
  }
})
</script>

<template>
  <DashboardHeader title="Detail de la reservation" />
  <main class="flex-1 overflow-auto p-6">
    <RouterLink to="/client/reservations" class="mb-6 inline-flex items-center gap-2 text-muted-foreground"><ArrowLeft class="h-4 w-4" />Retour aux reservations</RouterLink>
    <div v-if="!reservation" class="rounded-xl border border-border bg-card p-6">Reservation introuvable.</div>
    <div v-else class="grid grid-cols-1 gap-6 lg:grid-cols-3">
      <div class="space-y-6 lg:col-span-2">
        <div class="flex items-center gap-3 rounded-xl border p-4" :class="getStatusClass(reservation.status)"><component :is="getStatusIcon(reservation.status)" class="h-6 w-6" /><div><p class="font-semibold">{{ getStatusLabel(reservation.status) }}</p><p v-if="reservation.status === 'en_attente'" class="text-sm opacity-80">Votre demande est en cours de traitement</p></div></div>
        <div class="overflow-hidden rounded-xl border border-border bg-card"><div class="h-48"><img :src="reservation.property?.images?.[0] || '/placeholder.svg'" :alt="reservation.property?.title || ''" class="h-full w-full object-cover" /></div><div class="p-5"><h2 class="mb-2 text-xl font-semibold">{{ reservation.property?.title }}</h2><div class="mb-4 flex items-center gap-2 text-muted-foreground"><MapPin class="h-4 w-4" /><span>{{ reservation.property?.address }}, {{ reservation.property?.city }}</span></div><div class="flex items-center gap-6 text-sm text-muted-foreground"><div class="flex items-center gap-1"><Maximize class="h-4 w-4" />{{ reservation.property?.surface }} m2</div><div class="flex items-center gap-1"><Bed class="h-4 w-4" />{{ reservation.property?.bedrooms }} ch.</div><div class="flex items-center gap-1"><Bath class="h-4 w-4" />{{ reservation.property?.bathrooms }} sdb</div></div></div></div>
        <div class="rounded-xl border border-border bg-card p-5"><h3 class="mb-4 font-semibold">Details de la reservation</h3><div class="grid grid-cols-2 gap-4"><div><p class="mb-1 text-sm text-muted-foreground">Date de debut</p><p class="font-medium flex items-center gap-2"><Calendar class="h-4 w-4 text-primary" />{{ new Date(reservation.startDate || reservation.start_date).toLocaleDateString('fr-FR') }}</p></div><div><p class="mb-1 text-sm text-muted-foreground">Date de fin</p><p class="font-medium flex items-center gap-2"><Calendar class="h-4 w-4 text-primary" />{{ new Date(reservation.endDate || reservation.end_date).toLocaleDateString('fr-FR') }}</p></div><div><p class="mb-1 text-sm text-muted-foreground">Duree</p><p class="font-medium">{{ Math.ceil((new Date(reservation.endDate || reservation.end_date).getTime() - new Date(reservation.startDate || reservation.start_date).getTime()) / (1000 * 60 * 60 * 24 * 30)) }} mois</p></div><div><p class="mb-1 text-sm text-muted-foreground">Date de demande</p><p class="font-medium">{{ new Date(reservation.createdAt || reservation.created_at).toLocaleDateString('fr-FR') }}</p></div></div></div>
        <div v-if="reservation.agentComment || reservation.agent_comment" class="rounded-xl border border-border bg-card p-5"><h3 class="mb-3 flex items-center gap-2 font-semibold"><MessageSquare class="h-5 w-5 text-primary" />Commentaire de l'agent</h3><p class="text-muted-foreground">{{ reservation.agentComment || reservation.agent_comment }}</p></div>
      </div>
      <div class="lg:col-span-1"><div class="sticky top-6 rounded-xl border border-border bg-card p-5"><h3 class="mb-4 font-semibold">Resume financier</h3><div class="mb-4 space-y-3"><div class="flex justify-between text-sm"><span class="text-muted-foreground">Loyer mensuel</span><span>{{ Number(reservation.property?.price || reservation.property?.pricePerNight || 0).toLocaleString() }} FCFA</span></div><div class="flex justify-between text-sm"><span class="text-muted-foreground">Duree</span><span>{{ Math.ceil((new Date(reservation.endDate || reservation.end_date).getTime() - new Date(reservation.startDate || reservation.start_date).getTime()) / (1000 * 60 * 60 * 24 * 30)) }} mois</span></div><hr class="border-border" /><div class="flex justify-between font-semibold"><span>Total</span><span class="text-primary">{{ Number(reservation.totalPrice || reservation.total_price || 0).toLocaleString() }} FCFA</span></div></div><hr class="my-4 border-border" /><div class="space-y-3 text-sm"><div class="flex justify-between"><span class="text-muted-foreground">Reference</span><span class="font-medium">#{{ reservation.id }}</span></div><div class="flex justify-between"><span class="text-muted-foreground">Statut</span><span class="rounded-full px-2 py-0.5 text-xs font-medium" :class="getStatusClass(reservation.status)">{{ reservation.status }}</span></div></div><div v-if="reservation.status === 'confirmee'" class="mt-4"><RouterLink :to="`/client/reclamations/nouvelle?reservation=${reservation.id}`" class="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-input px-4 py-2.5 text-sm font-medium"><MessageSquare class="h-4 w-4" />Signaler un probleme</RouterLink></div></div></div>
    </div>
  </main>
</template>

// app/client/reservations/[id]/page.tsx
import Link from "next/link"
import Image from "next/image"
import { notFound } from "next/navigation"
import { 
  ArrowLeft, Calendar, Home, MapPin, Clock, CheckCircle, XCircle, Ban,
  MessageSquare, Bed, Bath, Maximize
} from "lucide-react"
import { DashboardHeader } from "@/components/dashboard-header"
import { mockReservations } from "@/lib/mock-data"
import type { ReservationStatus } from "@/lib/types"

interface ReservationDetailPageProps {
  params: Promise<{ id: string }>
}

export default async function ReservationDetailPage({ params }: ReservationDetailPageProps) {
  const { id } = await params
  const reservation = mockReservations.find(r => r.id === id)

  if (!reservation) {
    notFound()
  }

  const statusColors: Record<ReservationStatus, string> = {
    en_attente: "bg-yellow-100 text-yellow-800 border-yellow-200",
    confirmee: "bg-green-100 text-green-800 border-green-200",
    refusee: "bg-red-100 text-red-800 border-red-200",
    annulee: "bg-gray-100 text-gray-800 border-gray-200",
  }

  const statusLabels: Record<ReservationStatus, string> = {
    en_attente: "En attente de confirmation",
    confirmee: "Reservation confirmee",
    refusee: "Reservation refusee",
    annulee: "Reservation annulee",
  }

  const statusIcons: Record<ReservationStatus, React.ElementType> = {
    en_attente: Clock,
    confirmee: CheckCircle,
    refusee: XCircle,
    annulee: Ban,
  }

  const StatusIcon = statusIcons[reservation.status]

  // Calculer la duree
  const duration = Math.ceil((reservation.endDate.getTime() - reservation.startDate.getTime()) / (1000 * 60 * 60 * 24 * 30))

  return (
    <>
      <DashboardHeader title="Detail de la reservation" />

      <main className="flex-1 p-6 overflow-auto">
        <Link
          href="/client/reservations"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft className="h-4 w-4" />
          Retour aux reservations
        </Link>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Status Banner */}
            <div className={`flex items-center gap-3 p-4 rounded-xl border ${statusColors[reservation.status]}`}>
              <StatusIcon className="h-6 w-6" />
              <div>
                <p className="font-semibold">{statusLabels[reservation.status]}</p>
                {reservation.status === "en_attente" && (
                  <p className="text-sm opacity-80">Votre demande est en cours de traitement</p>
                )}
              </div>
            </div>

            {/* Property Info */}
            <div className="bg-card rounded-xl border border-border overflow-hidden">
              <div className="relative h-48">
                <Image
                  src={reservation.property?.images[0] || "/placeholder.svg"}
                  alt={reservation.property?.title || ""}
                  fill
                  className="object-cover"
                />
              </div>
              <div className="p-5">
                <h2 className="text-xl font-semibold text-foreground mb-2">
                  {reservation.property?.title}
                </h2>
                <div className="flex items-center gap-2 text-muted-foreground mb-4">
                  <MapPin className="h-4 w-4" />
                  <span>{reservation.property?.address}, {reservation.property?.city}</span>
                </div>
                <div className="flex items-center gap-6 text-sm text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Maximize className="h-4 w-4" />
                    <span>{reservation.property?.surface} m2</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Bed className="h-4 w-4" />
                    <span>{reservation.property?.bedrooms} ch.</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Bath className="h-4 w-4" />
                    <span>{reservation.property?.bathrooms} sdb</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Reservation Details */}
            <div className="bg-card rounded-xl border border-border p-5">
              <h3 className="font-semibold text-foreground mb-4">Details de la reservation</h3>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de debut</p>
                  <p className="font-medium text-foreground flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-primary" />
                    {reservation.startDate.toLocaleDateString("fr-FR", {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric"
                    })}
                  </p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de fin</p>
                  <p className="font-medium text-foreground flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-primary" />
                    {reservation.endDate.toLocaleDateString("fr-FR", {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric"
                    })}
                  </p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Duree</p>
                  <p className="font-medium text-foreground">{duration} mois</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de demande</p>
                  <p className="font-medium text-foreground">
                    {reservation.createdAt.toLocaleDateString("fr-FR")}
                  </p>
                </div>
              </div>
            </div>

            {/* Agent Comment */}
            {reservation.agentComment && (
              <div className="bg-card rounded-xl border border-border p-5">
                <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
                  <MessageSquare className="h-5 w-5 text-primary" />
                  Commentaire de l&apos;agent
                </h3>
                <p className="text-muted-foreground">{reservation.agentComment}</p>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            <div className="bg-card rounded-xl border border-border p-5 sticky top-6">
              <h3 className="font-semibold text-foreground mb-4">Resume financier</h3>
              
              <div className="space-y-3 mb-4">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Loyer mensuel</span>
                  <span className="text-foreground">{reservation.property?.price.toLocaleString()} EUR</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Duree</span>
                  <span className="text-foreground">{duration} mois</span>
                </div>
                <hr className="border-border" />
                <div className="flex justify-between font-semibold">
                  <span className="text-foreground">Total</span>
                  <span className="text-primary">{reservation.totalPrice.toLocaleString()} EUR</span>
                </div>
              </div>

              <hr className="border-border my-4" />

              <div className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Reference</span>
                  <span className="text-foreground font-medium">#{reservation.id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Statut</span>
                  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColors[reservation.status]}`}>
                    {reservation.status === "en_attente" ? "En attente" : 
                     reservation.status === "confirmee" ? "Confirmee" :
                     reservation.status === "refusee" ? "Refusee" : "Annulee"}
                  </span>
                </div>
              </div>

              {reservation.status === "confirmee" && (
                <>
                  <hr className="border-border my-4" />
                  <Link
                    href={`/client/reclamations/nouvelle?reservation=${reservation.id}`}
                    className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 border border-input rounded-lg text-sm font-medium text-foreground hover:bg-muted transition-colors"
                  >
                    <MessageSquare className="h-4 w-4" />
                    Signaler un probleme
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
