// frontend-vue/src/app/agent/reservations/[id]/page.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowLeft, CalendarDays, CheckCircle2, Clock, Home, MessageSquare, XCircle } from 'lucide-vue-next'
import DashboardHeader from '@/components/DashboardHeader.vue'
import { getDetail, updateReservation } from '@/lib/api'

const route = useRoute()
const loading = ref(true)
const saving = ref(false)
const feedback = ref<string | null>(null)
const reservation = ref<any | null>(null)

const reservationId = computed(() => String(route.params.id ?? ''))

const loadReservation = async () => {
  loading.value = true
  feedback.value = null

  try {
    reservation.value = await getDetail('/reservations', reservationId.value)
  } catch (error) {
    feedback.value = error instanceof Error ? error.message : 'Impossible de charger la reservation.'
    reservation.value = null
  } finally {
    loading.value = false
  }
}

const setStatus = async (status: 'confirmee' | 'refusee') => {
  if (!reservation.value) return

  saving.value = true
  feedback.value = null

  try {
    reservation.value = await updateReservation({ id: reservationId.value, status })
    feedback.value = status === 'confirmee' ? 'Reservation acceptee.' : 'Reservation refusee.'
  } catch (error) {
    feedback.value = error instanceof Error ? error.message : 'Action impossible.'
  } finally {
    saving.value = false
  }
}

onMounted(loadReservation)
</script>

<template>
  <DashboardHeader title="Detail reservation" subtitle="Traitez la demande attribuee a votre compte agent" />

  <main class="flex-1 overflow-auto p-6">
    <RouterLink to="/agent/reservations" class="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
      <ArrowLeft class="h-4 w-4" />
      Retour aux reservations
    </RouterLink>

    <div v-if="loading" class="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">
      Chargement...
    </div>

    <div v-else-if="!reservation" class="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">
      Reservation introuvable.
    </div>

    <div v-else class="grid gap-6 lg:grid-cols-[1.4fr_0.9fr]">
      <section class="space-y-6 rounded-xl border border-border bg-card p-6">
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p class="text-xs uppercase tracking-[0.24em] text-muted-foreground">Reservation #{{ reservation.id }}</p>
            <h1 class="mt-2 text-3xl font-bold text-foreground">{{ reservation.property?.title }}</h1>
            <p class="mt-1 text-muted-foreground">{{ reservation.property?.city }}</p>
          </div>
          <span class="inline-flex items-center gap-2 rounded-full px-3 py-1 text-sm font-medium"
                :class="reservation.status === 'confirmee' ? 'bg-green-100 text-green-700' : reservation.status === 'refusee' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'">
            <Clock v-if="reservation.status === 'en_attente'" class="h-4 w-4" />
            <CheckCircle2 v-else-if="reservation.status === 'confirmee'" class="h-4 w-4" />
            <XCircle v-else class="h-4 w-4" />
            {{ reservation.status }}
          </span>
        </div>

        <div v-if="feedback" class="rounded-lg border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800">
          {{ feedback }}
        </div>

        <div class="grid gap-4 md:grid-cols-2">
          <article class="rounded-2xl border border-border bg-background p-4">
            <p class="text-xs uppercase tracking-[0.2em] text-muted-foreground">Client</p>
            <p class="mt-2 font-semibold">{{ reservation.client?.first_name ?? reservation.client?.firstName }} {{ reservation.client?.last_name ?? reservation.client?.lastName }}</p>
            <p class="text-sm text-muted-foreground">{{ reservation.client?.email }}</p>
          </article>
          <article class="rounded-2xl border border-border bg-background p-4">
            <p class="text-xs uppercase tracking-[0.2em] text-muted-foreground">Agent assigné</p>
            <p class="mt-2 font-semibold">{{ reservation.agent?.name ?? 'Non défini' }}</p>
            <p class="text-sm text-muted-foreground">{{ reservation.agent?.email ?? 'Aucun agent' }}</p>
          </article>
          <article class="rounded-2xl border border-border bg-background p-4">
            <p class="text-xs uppercase tracking-[0.2em] text-muted-foreground">Dates</p>
            <p class="mt-2 font-semibold">{{ new Date(reservation.start_date || reservation.startDate).toLocaleDateString('fr-FR') }}</p>
            <p class="text-sm text-muted-foreground">au {{ new Date(reservation.end_date || reservation.endDate).toLocaleDateString('fr-FR') }}</p>
          </article>
          <article class="rounded-2xl border border-border bg-background p-4">
            <p class="text-xs uppercase tracking-[0.2em] text-muted-foreground">Montant</p>
            <p class="mt-2 font-semibold">{{ Number(reservation.total_price || reservation.totalPrice || 0).toLocaleString() }} FCFA</p>
          </article>
        </div>

        <article v-if="reservation.commentaire_agent || reservation.agent_comment" class="rounded-2xl border border-border bg-background p-4">
          <p class="text-xs uppercase tracking-[0.2em] text-muted-foreground">Commentaire agent</p>
          <p class="mt-2 text-sm text-foreground">{{ reservation.commentaire_agent || reservation.agent_comment }}</p>
        </article>

        <div class="flex flex-wrap gap-3">
          <button
            type="button"
            :disabled="saving || reservation.status === 'confirmee'"
            class="inline-flex items-center gap-2 rounded-full bg-green-600 px-5 py-3 text-sm font-semibold text-white transition-opacity disabled:cursor-not-allowed disabled:opacity-50"
            @click="setStatus('confirmee')"
          >
            <CheckCircle2 class="h-4 w-4" />
            Accepter
          </button>
          <button
            type="button"
            :disabled="saving || reservation.status === 'refusee'"
            class="inline-flex items-center gap-2 rounded-full bg-red-600 px-5 py-3 text-sm font-semibold text-white transition-opacity disabled:cursor-not-allowed disabled:opacity-50"
            @click="setStatus('refusee')"
          >
            <XCircle class="h-4 w-4" />
            Refuser
          </button>
        </div>
      </section>

      <aside class="space-y-6">
        <article class="rounded-xl border border-border bg-card p-6">
          <div class="flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10">
              <Home class="h-6 w-6 text-primary" />
            </div>
            <div>
              <p class="text-sm text-muted-foreground">Bien concerné</p>
              <p class="font-semibold">{{ reservation.property?.title }}</p>
            </div>
          </div>
          <div class="mt-4 space-y-2 text-sm text-muted-foreground">
            <p>Ville: {{ reservation.property?.city }}</p>
            <p>Reference: #{{ reservation.property_id || reservation.propertyId }}</p>
          </div>
        </article>

        <article class="rounded-xl border border-border bg-card p-6">
          <div class="flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100">
              <CalendarDays class="h-6 w-6 text-amber-700" />
            </div>
            <div>
              <p class="text-sm text-muted-foreground">Statut métier</p>
              <p class="font-semibold capitalize">{{ reservation.status }}</p>
            </div>
          </div>
          <p class="mt-4 text-sm text-muted-foreground">
            Une fois la reservation acceptee, le client voit la confirmation dans son espace.
          </p>
        </article>

        <article class="rounded-xl border border-border bg-card p-6">
          <div class="flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-100">
              <MessageSquare class="h-6 w-6 text-blue-600" />
            </div>
            <div>
              <p class="text-sm text-muted-foreground">Client</p>
              <p class="font-semibold">{{ reservation.client?.email }}</p>
            </div>
          </div>
        </article>
      </aside>
    </div>
  </main>
</template>

// app/client/reservations/[id]/page.tsx
import Link from "next/link"
import Image from "next/image"
import { notFound } from "next/navigation"
import { 
  ArrowLeft, Calendar, Home, MapPin, Clock, CheckCircle, XCircle, Ban,
  MessageSquare, Bed, Bath, Maximize
} from "lucide-react"
import { DashboardHeader } from "@/components/dashboard-header"
import { mockReservations, mockProperties } from "@/lib/mock-data"
import type { ReservationStatus } from "@/lib/types"

interface ReservationDetailPageProps {
  params: Promise<{ id: string }>
}

export default async function ReservationDetailPage({ params }: ReservationDetailPageProps) {
  const { id } = await params
  const reservation = mockReservations.find(r => r.id === id)

  if (!reservation) {
    notFound()
  }

  const property = mockProperties.find(p => p.id === reservation.propertyId)

  const statusColors: Record<ReservationStatus, string> = {
    en_attente: "bg-yellow-100 text-yellow-800 border-yellow-200",
    confirmee: "bg-green-100 text-green-800 border-green-200",
    refusee: "bg-red-100 text-red-800 border-red-200",
    annulee: "bg-gray-100 text-gray-800 border-gray-200",
  }

  const statusLabels: Record<ReservationStatus, string> = {
    en_attente: "En attente de confirmation",
    confirmee: "Reservation confirmee",
    refusee: "Reservation refusee",
    annulee: "Reservation annulee",
  }

  const statusIcons: Record<ReservationStatus, React.ElementType> = {
    en_attente: Clock,
    confirmee: CheckCircle,
    refusee: XCircle,
    annulee: Ban,
  }

  const StatusIcon = statusIcons[reservation.status]

  // Calculer la duree
  const start = new Date(reservation.startDate)
  const end = new Date(reservation.endDate)
  const duration = Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24 * 30))

  return (
    <>
      <DashboardHeader title="Detail de la reservation" />

      <main className="flex-1 p-6 overflow-auto">
        <Link
          href="/client/reservations"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft className="h-4 w-4" />
          Retour aux reservations
        </Link>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Status Banner */}
            <div className={`flex items-center gap-3 p-4 rounded-xl border ${statusColors[reservation.status]}`}>
              <StatusIcon className="h-6 w-6" />
              <div>
                <p className="font-semibold">{statusLabels[reservation.status]}</p>
                {reservation.status === "en_attente" && (
                  <p className="text-sm opacity-80">Votre demande est en cours de traitement</p>
                )}
              </div>
            </div>

            {/* Property Info */}
            <div className="bg-card rounded-xl border border-border overflow-hidden">
              <div className="relative h-48">
                <Image
                  src={property?.images[0] || "/placeholder.svg"}
                  alt={property?.title || ""}
                  fill
                  className="object-cover"
                />
              </div>
              <div className="p-5">
                <h2 className="text-xl font-semibold text-foreground mb-2">
                  {property?.title}
                </h2>
                <div className="flex items-center gap-2 text-muted-foreground mb-4">
                  <MapPin className="h-4 w-4" />
                  <span>{property?.address}, {property?.city}</span>
                </div>
                <div className="flex items-center gap-6 text-sm text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Maximize className="h-4 w-4" />
                    <span>{property?.surface} m2</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Bed className="h-4 w-4" />
                    <span>{property?.bedrooms} ch.</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Bath className="h-4 w-4" />
                    <span>{property?.bathrooms} sdb</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Reservation Details */}
            <div className="bg-card rounded-xl border border-border p-5">
              <h3 className="font-semibold text-foreground mb-4">Details de la reservation</h3>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de debut</p>
                  <p className="font-medium text-foreground flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-primary" />
                    {new Date(reservation.startDate).toLocaleDateString("fr-FR", {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric"
                    })}
                  </p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de fin</p>
                  <p className="font-medium text-foreground flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-primary" />
                    {new Date(reservation.endDate).toLocaleDateString("fr-FR", {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric"
                    })}
                  </p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Duree</p>
                  <p className="font-medium text-foreground">{duration} mois</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground mb-1">Date de demande</p>
                  <p className="font-medium text-foreground">
                    {new Date(reservation.createdAt).toLocaleDateString("fr-FR")}
                  </p>
                </div>
              </div>
            </div>

            {/* Agent Comment */}
            {reservation.agentComment && (
              <div className="bg-card rounded-xl border border-border p-5">
                <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
                  <MessageSquare className="h-5 w-5 text-primary" />
                  Commentaire de l&apos;agent
                </h3>
                <p className="text-muted-foreground">{reservation.agentComment}</p>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            <div className="bg-card rounded-xl border border-border p-5 sticky top-6">
              <h3 className="font-semibold text-foreground mb-4">Resume financier</h3>
              
              <div className="space-y-3 mb-4">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Loyer mensuel</span>
                  <span className="text-foreground">{property?.pricePerNight.toLocaleString()} EUR</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Duree</span>
                  <span className="text-foreground">{duration} mois</span>
                </div>
                <hr className="border-border" />
                <div className="flex justify-between font-semibold">
                  <span className="text-foreground">Total</span>
                  <span className="text-primary">{reservation.totalPrice.toLocaleString()} EUR</span>
                </div>
              </div>

              <hr className="border-border my-4" />

              <div className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Reference</span>
                  <span className="text-foreground font-medium">#{reservation.id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Statut</span>
                  <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColors[reservation.status]}`}>
                    {reservation.status === "en_attente" ? "En attente" : 
                     reservation.status === "confirmee" ? "Confirmee" :
                     reservation.status === "refusee" ? "Refusee" : "Annulee"}
                  </span>
                </div>
              </div>

              {reservation.status === "confirmee" && (
                <>
                  <hr className="border-border my-4" />
                  <Link
                    href={`/client/reclamations/nouvelle?reservation=${reservation.id}`}
                    className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 border border-input rounded-lg text-sm font-medium text-foreground hover:bg-muted transition-colors"
                  >
                    <MessageSquare className="h-4 w-4" />
                    Signaler un probleme
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
