// app/client/profil/page.tsx
"use client"

import { useState } from "react"
import { User, Mail, Phone, Lock, Eye, EyeOff, Save, CheckCircle } from "lucide-react"
import { DashboardHeader } from "@/components/dashboard-header"

export default function ClientProfilePage() {
  const [isEditing, setIsEditing] = useState(false)
  const [showPasswordForm, setShowPasswordForm] = useState(false)
  const [showCurrentPassword, setShowCurrentPassword] = useState(false)
  const [showNewPassword, setShowNewPassword] = useState(false)
  const [saveSuccess, setSaveSuccess] = useState(false)

  const [profileData, setProfileData] = useState({
    firstName: "Sophie",
    lastName: "Leroy",
    email: "sophie.leroy@email.com",
    phone: "06 12 34 56 78",
  })

  const [passwordData, setPasswordData] = useState({
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  })

  const handleProfileSave = async () => {
    // Simulation de sauvegarde
    await new Promise(resolve => setTimeout(resolve, 1000))
    setIsEditing(false)
    setSaveSuccess(true)
    setTimeout(() => setSaveSuccess(false), 3000)
  }

  const handlePasswordChange = async (e: React.FormEvent) => {
    e.preventDefault()
    // Simulation de changement de mot de passe
    await new Promise(resolve => setTimeout(resolve, 1000))
    setPasswordData({ currentPassword: "", newPassword: "", confirmPassword: "" })
    setShowPasswordForm(false)
    setSaveSuccess(true)
    setTimeout(() => setSaveSuccess(false), 3000)
  }

  return (
    <>
      <DashboardHeader title="Mon profil" subtitle="Gerez vos informations personnelles" />

      <main className="flex-1 p-6 overflow-auto">
        {saveSuccess && (
          <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg flex items-center gap-3 text-green-800">
            <CheckCircle className="h-5 w-5" />
            <span>Modifications enregistrees avec succes</span>
          </div>
        )}

        <div className="max-w-2xl space-y-6">
          {/* Profile Info */}
          <div className="bg-card rounded-xl border border-border">
            <div className="flex items-center justify-between p-5 border-b border-border">
              <h2 className="font-semibold text-foreground">Informations personnelles</h2>
              {!isEditing ? (
                <button
                  onClick={() => setIsEditing(true)}
                  className="px-4 py-2 text-sm font-medium text-primary hover:text-primary/80 transition-colors"
                >
                  Modifier
                </button>
              ) : (
                <div className="flex gap-2">
                  <button
                    onClick={() => setIsEditing(false)}
                    className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Annuler
                  </button>
                  <button
                    onClick={handleProfileSave}
                    className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
                  >
                    <Save className="h-4 w-4" />
                    Enregistrer
                  </button>
                </div>
              )}
            </div>

            <div className="p-5 space-y-5">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center">
                  <User className="h-10 w-10 text-primary" />
                </div>
                {isEditing && (
                  <button className="text-sm text-primary hover:text-primary/80">
                    Changer la photo
                  </button>
                )}
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Prenom</label>
                  {isEditing ? (
                    <input
                      type="text"
                      value={profileData.firstName}
                      onChange={(e) => setProfileData({ ...profileData, firstName: e.target.value })}
                      className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    />
                  ) : (
                    <p className="text-foreground">{profileData.firstName}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">Nom</label>
                  {isEditing ? (
                    <input
                      type="text"
                      value={profileData.lastName}
                      onChange={(e) => setProfileData({ ...profileData, lastName: e.target.value })}
                      className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    />
                  ) : (
                    <p className="text-foreground">{profileData.lastName}</p>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-foreground mb-2">
                  <Mail className="inline h-4 w-4 mr-1" />
                  Email
                </label>
                {isEditing ? (
                  <input
                    type="email"
                    value={profileData.email}
                    onChange={(e) => setProfileData({ ...profileData, email: e.target.value })}
                    className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                ) : (
                  <p className="text-foreground">{profileData.email}</p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-foreground mb-2">
                  <Phone className="inline h-4 w-4 mr-1" />
                  Telephone
                </label>
                {isEditing ? (
                  <input
                    type="tel"
                    value={profileData.phone}
                    onChange={(e) => setProfileData({ ...profileData, phone: e.target.value })}
                    className="w-full px-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                ) : (
                  <p className="text-foreground">{profileData.phone}</p>
                )}
              </div>
            </div>
          </div>

          {/* Password Change */}
          <div className="bg-card rounded-xl border border-border">
            <div className="flex items-center justify-between p-5 border-b border-border">
              <div>
                <h2 className="font-semibold text-foreground">Mot de passe</h2>
                <p className="text-sm text-muted-foreground mt-1">Modifiez votre mot de passe</p>
              </div>
              {!showPasswordForm && (
                <button
                  onClick={() => setShowPasswordForm(true)}
                  className="px-4 py-2 text-sm font-medium text-primary hover:text-primary/80 transition-colors"
                >
                  Modifier
                </button>
              )}
            </div>

            {showPasswordForm && (
              <form onSubmit={handlePasswordChange} className="p-5 space-y-4">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Mot de passe actuel
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                    <input
                      type={showCurrentPassword ? "text" : "password"}
                      required
                      value={passwordData.currentPassword}
                      onChange={(e) => setPasswordData({ ...passwordData, currentPassword: e.target.value })}
                      className="w-full pl-10 pr-10 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    />
                    <button
                      type="button"
                      onClick={() => setShowCurrentPassword(!showCurrentPassword)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                    >
                      {showCurrentPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Nouveau mot de passe
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                    <input
                      type={showNewPassword ? "text" : "password"}
                      required
                      minLength={8}
                      value={passwordData.newPassword}
                      onChange={(e) => setPasswordData({ ...passwordData, newPassword: e.target.value })}
                      className="w-full pl-10 pr-10 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    />
                    <button
                      type="button"
                      onClick={() => setShowNewPassword(!showNewPassword)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                    >
                      {showNewPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Confirmer le nouveau mot de passe
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                    <input
                      type="password"
                      required
                      value={passwordData.confirmPassword}
                      onChange={(e) => setPasswordData({ ...passwordData, confirmPassword: e.target.value })}
                      className="w-full pl-10 pr-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    />
                  </div>
                </div>

                <div className="flex gap-3 pt-2">
                  <button
                    type="button"
                    onClick={() => setShowPasswordForm(false)}
                    className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Annuler
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
                  >
                    Changer le mot de passe
                  </button>
                </div>
              </form>
            )}
          </div>

          {/* Account Info */}
          <div className="bg-card rounded-xl border border-border p-5">
            <h2 className="font-semibold text-foreground mb-4">Informations du compte</h2>
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Date d&apos;inscription</span>
                <span className="text-foreground">10 janvier 2024</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Derniere connexion</span>
                <span className="text-foreground">Aujourd&apos;hui a 14:30</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Statut du compte</span>
                <span className="px-2 py-0.5 bg-green-100 text-green-800 rounded-full text-xs font-medium">
                  Actif
                </span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

// frontend-vue/src/app/client/profil/page.vue
<script setup lang="ts">
import { ref } from 'vue'
import { User, Mail, Phone, Lock, Eye, EyeOff, Save, CheckCircle } from 'lucide-vue-next'
import DashboardHeader from '@/components/DashboardHeader.vue'

const isEditing = ref(false)
const showPasswordForm = ref(false)
const showCurrentPassword = ref(false)
const showNewPassword = ref(false)
const saveSuccess = ref(false)

const profileData = ref({
  firstName: 'Sophie',
  lastName: 'Leroy',
  email: 'sophie.leroy@email.com',
  phone: '06 12 34 56 78',
})

const passwordData = ref({
  currentPassword: '',
  newPassword: '',
  confirmPassword: '',
})

const handleProfileSave = async () => {
  await new Promise((resolve) => setTimeout(resolve, 1000))
  isEditing.value = false
  saveSuccess.value = true
  setTimeout(() => (saveSuccess.value = false), 3000)
}

const handlePasswordChange = async (e: Event) => {
  e.preventDefault()
  await new Promise((resolve) => setTimeout(resolve, 1000))
  passwordData.value = { currentPassword: '', newPassword: '', confirmPassword: '' }
  showPasswordForm.value = false
  saveSuccess.value = true
  setTimeout(() => (saveSuccess.value = false), 3000)
}
</script>

<template>
  <DashboardHeader title="Mon profil" subtitle="Gerez vos informations personnelles" />

  <main class="flex-1 p-6 overflow-auto">
    <div v-if="saveSuccess" class="mb-6 flex items-center gap-3 rounded-lg border border-green-200 bg-green-50 p-4 text-green-800">
      <CheckCircle class="h-5 w-5" />
      <span>Modifications enregistrees avec succes</span>
    </div>

    <div class="max-w-2xl space-y-6">
      <div class="rounded-xl border border-border bg-card">
        <div class="flex items-center justify-between border-b border-border p-5">
          <h2 class="font-semibold text-foreground">Informations personnelles</h2>
          <button v-if="!isEditing" class="px-4 py-2 text-sm font-medium text-primary" @click="isEditing = true">Modifier</button>
          <div v-else class="flex gap-2">
            <button class="px-4 py-2 text-sm font-medium text-muted-foreground" @click="isEditing = false">Annuler</button>
            <button class="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground" @click="handleProfileSave">
              <Save class="h-4 w-4" />
              Enregistrer
            </button>
          </div>
        </div>

        <div class="space-y-5 p-5">
          <div class="mb-6 flex items-center gap-4">
            <div class="flex h-20 w-20 items-center justify-center rounded-full bg-primary/10">
              <User class="h-10 w-10 text-primary" />
            </div>
          </div>

          <div class="grid gap-4 sm:grid-cols-2">
            <div>
              <label class="mb-2 block text-sm font-medium text-foreground">Prenom</label>
              <input v-if="isEditing" v-model="profileData.firstName" class="w-full rounded-lg border border-input bg-background px-4 py-2.5" type="text" />
              <p v-else class="text-foreground">{{ profileData.firstName }}</p>
            </div>
            <div>
              <label class="mb-2 block text-sm font-medium text-foreground">Nom</label>
              <input v-if="isEditing" v-model="profileData.lastName" class="w-full rounded-lg border border-input bg-background px-4 py-2.5" type="text" />
              <p v-else class="text-foreground">{{ profileData.lastName }}</p>
            </div>
          </div>

          <div>
            <label class="mb-2 block text-sm font-medium text-foreground"><Mail class="mr-1 inline h-4 w-4" />Email</label>
            <input v-if="isEditing" v-model="profileData.email" class="w-full rounded-lg border border-input bg-background px-4 py-2.5" type="email" />
            <p v-else class="text-foreground">{{ profileData.email }}</p>
          </div>

          <div>
            <label class="mb-2 block text-sm font-medium text-foreground"><Phone class="mr-1 inline h-4 w-4" />Telephone</label>
            <input v-if="isEditing" v-model="profileData.phone" class="w-full rounded-lg border border-input bg-background px-4 py-2.5" type="tel" />
            <p v-else class="text-foreground">{{ profileData.phone }}</p>
          </div>
        </div>
      </div>

      <div class="rounded-xl border border-border bg-card">
        <div class="flex items-center justify-between border-b border-border p-5">
          <div>
            <h2 class="font-semibold text-foreground">Mot de passe</h2>
            <p class="mt-1 text-sm text-muted-foreground">Modifiez votre mot de passe</p>
          </div>
          <button v-if="!showPasswordForm" class="px-4 py-2 text-sm font-medium text-primary" @click="showPasswordForm = true">Modifier</button>
        </div>

        <form v-if="showPasswordForm" class="space-y-4 p-5" @submit="handlePasswordChange">
          <div>
            <label class="mb-2 block text-sm font-medium text-foreground">Mot de passe actuel</label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
              <input v-model="passwordData.currentPassword" :type="showCurrentPassword ? 'text' : 'password'" class="w-full rounded-lg border border-input bg-background py-2.5 pl-10 pr-10" />
              <button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" @click="showCurrentPassword = !showCurrentPassword">
                <EyeOff v-if="showCurrentPassword" class="h-5 w-5" />
                <Eye v-else class="h-5 w-5" />
              </button>
            </div>
          </div>

          <div>
            <label class="mb-2 block text-sm font-medium text-foreground">Nouveau mot de passe</label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
              <input v-model="passwordData.newPassword" :type="showNewPassword ? 'text' : 'password'" minlength="8" class="w-full rounded-lg border border-input bg-background py-2.5 pl-10 pr-10" />
              <button type="button" class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" @click="showNewPassword = !showNewPassword">
                <EyeOff v-if="showNewPassword" class="h-5 w-5" />
                <Eye v-else class="h-5 w-5" />
              </button>
            </div>
          </div>

          <div>
            <label class="mb-2 block text-sm font-medium text-foreground">Confirmer le nouveau mot de passe</label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
              <input v-model="passwordData.confirmPassword" type="password" class="w-full rounded-lg border border-input bg-background py-2.5 pl-10 pr-4" />
            </div>
          </div>

          <div class="flex gap-3 pt-2">
            <button type="button" class="px-4 py-2 text-sm font-medium text-muted-foreground" @click="showPasswordForm = false">Annuler</button>
            <button type="submit" class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Changer le mot de passe</button>
          </div>
        </form>
      </div>

      <div class="rounded-xl border border-border bg-card p-5">
        <h2 class="mb-4 font-semibold text-foreground">Informations du compte</h2>
        <div class="space-y-3 text-sm">
          <div class="flex justify-between"><span class="text-muted-foreground">Date d'inscription</span><span class="text-foreground">10 janvier 2024</span></div>
          <div class="flex justify-between"><span class="text-muted-foreground">Derniere connexion</span><span class="text-foreground">Aujourd'hui a 14:30</span></div>
          <div class="flex justify-between"><span class="text-muted-foreground">Statut du compte</span><span class="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800">Actif</span></div>
        </div>
      </div>
    </div>
  </main>
</template>
