// app/biens/page.tsx
"use client"

import { useState, useMemo } from "react"
import { Search, SlidersHorizontal, X } from "lucide-react"
import { PublicHeader } from "@/components/public-header"
import { PublicFooter } from "@/components/public-footer"
import { PropertyCard } from "@/components/property-card"
import { mockProperties, mockOptions } from "@/lib/mock-data"

export default function PropertiesPage() {
  const [searchCity, setSearchCity] = useState("")
  const [priceRange, setPriceRange] = useState<[number, number]>([0, 5000])
  const [selectedOptions, setSelectedOptions] = useState<string[]>([])
  const [showFilters, setShowFilters] = useState(false)
  const [sortBy, setSortBy] = useState<"price-asc" | "price-desc" | "newest">("newest")

  const filteredProperties = useMemo(() => {
    let result = mockProperties.filter(p => p.status === "disponible")

    if (searchCity) {
      result = result.filter(p =>
        p.city.toLowerCase().includes(searchCity.toLowerCase()) ||
        p.postalCode.includes(searchCity)
      )
    }

    result = result.filter(p => p.price >= priceRange[0] && p.price <= priceRange[1])

    if (selectedOptions.length > 0) {
      result = result.filter(p =>
        selectedOptions.every(optId => p.options.some(opt => opt.id === optId))
      )
    }

    switch (sortBy) {
      case "price-asc":
        result.sort((a, b) => a.price - b.price)
        break
      case "price-desc":
        result.sort((a, b) => b.price - a.price)
        break
      case "newest":
        result.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
        break
    }

    return result
  }, [searchCity, priceRange, selectedOptions, sortBy])

  const toggleOption = (optionId: string) => {
    setSelectedOptions(prev =>
      prev.includes(optionId)
        ? prev.filter(id => id !== optionId)
        : [...prev, optionId]
    )
  }

  const clearFilters = () => {
    setSearchCity("")
    setPriceRange([0, 5000])
    setSelectedOptions([])
    setSortBy("newest")
  }

  return (
    <div className="min-h-screen flex flex-col">
      <PublicHeader />

      <main className="flex-1 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground mb-2">Nos biens disponibles</h1>
            <p className="text-muted-foreground">
              {filteredProperties.length} bien{filteredProperties.length > 1 ? "s" : ""} disponible{filteredProperties.length > 1 ? "s" : ""}
            </p>
          </div>

          {/* Search and Filters */}
          <div className="bg-card rounded-xl border border-border p-4 mb-8">
            <div className="flex flex-col lg:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="Rechercher par ville ou code postal..."
                  value={searchCity}
                  onChange={(e) => setSearchCity(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 bg-background border border-input rounded-lg text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </div>

              <div className="flex gap-4">
                <select
                  value={sortBy}
                  onChange={(e) => setSortBy(e.target.value as typeof sortBy)}
                  className="px-4 py-2.5 bg-background border border-input rounded-lg text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                >
                  <option value="newest">Plus recents</option>
                  <option value="price-asc">Prix croissant</option>
                  <option value="price-desc">Prix decroissant</option>
                </select>

                <button
                  onClick={() => setShowFilters(!showFilters)}
                  className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-lg border transition-colors ${
                    showFilters || selectedOptions.length > 0
                      ? "bg-primary text-primary-foreground border-primary"
                      : "bg-background border-input text-foreground hover:bg-muted"
                  }`}
                >
                  <SlidersHorizontal className="h-5 w-5" />
                  Filtres
                  {selectedOptions.length > 0 && (
                    <span className="bg-primary-foreground text-primary px-1.5 py-0.5 rounded text-xs font-medium">
                      {selectedOptions.length}
                    </span>
                  )}
                </button>
              </div>
            </div>

            {/* Extended Filters */}
            {showFilters && (
              <div className="mt-4 pt-4 border-t border-border">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-foreground mb-3">
                      Budget: {priceRange[0]} EUR - {priceRange[1]} EUR/mois
                    </label>
                    <div className="flex gap-4">
                      <input
                        type="range"
                        min="0"
                        max="5000"
                        step="100"
                        value={priceRange[0]}
                        onChange={(e) => setPriceRange([Number(e.target.value), priceRange[1]])}
                        className="flex-1"
                      />
                      <input
                        type="range"
                        min="0"
                        max="5000"
                        step="100"
                        value={priceRange[1]}
                        onChange={(e) => setPriceRange([priceRange[0], Number(e.target.value)])}
                        className="flex-1"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-foreground mb-3">Options</label>
                    <div className="flex flex-wrap gap-2">
                      {mockOptions.map((option) => (
                        <button
                          key={option.id}
                          onClick={() => toggleOption(option.id)}
                          className={`px-3 py-1.5 rounded-lg text-sm transition-colors ${
                            selectedOptions.includes(option.id)
                              ? "bg-primary text-primary-foreground"
                              : "bg-secondary text-secondary-foreground hover:bg-secondary/80"
                          }`}
                        >
                          {option.name}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="mt-4 flex justify-end">
                  <button
                    onClick={clearFilters}
                    className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <X className="h-4 w-4" />
                    Effacer les filtres
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Properties Grid */}
          {filteredProperties.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredProperties.map((property) => (
                <PropertyCard key={property.id} property={property} />
              ))}
            </div>
          ) : (
            <div className="text-center py-16">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-muted rounded-full mb-4">
                <Search className="h-8 w-8 text-muted-foreground" />
              </div>
              <h3 className="text-lg font-semibold text-foreground mb-2">Aucun bien trouve</h3>
              <p className="text-muted-foreground mb-4">
                Essayez de modifier vos criteres de recherche
              </p>
              <button
                onClick={clearFilters}
                className="text-primary hover:text-primary/80 font-medium"
              >
                Effacer tous les filtres
              </button>
            </div>
          )}
        </div>
      </main>

      <PublicFooter />
    </div>
  )
}

// frontend-vue/src/app/biens/page.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Search, SlidersHorizontal, Sparkles, X } from 'lucide-vue-next'
import PublicHeader from '@/components/PublicHeader.vue'
import PublicFooter from '@/components/PublicFooter.vue'
import PropertyCard from '@/components/PropertyCard.vue'
import { getList, getProperties } from '@/lib/api'

const route = useRoute()
const router = useRouter()
const priceLimit = 500000

const searchCity = ref('')
const priceRange = ref<[number, number]>([0, priceLimit])
const selectedOptions = ref<string[]>([])
const showFilters = ref(false)
const sortBy = ref<'price-asc' | 'price-desc' | 'newest'>('newest')
const properties = ref<any[]>([])
const options = ref<any[]>([])

const filteredProperties = computed(() => {
  let result = properties.value.filter((property) => property.status === 'disponible')

  if (searchCity.value) {
    const term = searchCity.value.toLowerCase()
    result = result.filter((property) => {
      const postalCode = property.postal_code || property.postalCode || ''
      return property.city.toLowerCase().includes(term)
        || property.address.toLowerCase().includes(term)
        || postalCode.includes(searchCity.value)
        || property.title.toLowerCase().includes(term)
    })
  }

  result = result.filter((property) => property.price >= priceRange.value[0] && property.price <= priceRange.value[1])

  if (selectedOptions.value.length > 0) {
    result = result.filter((property) => selectedOptions.value.every((optionId) => (property.options || []).some((option: any) => option.id === optionId)))
  }

  const sorted = [...result]
  switch (sortBy.value) {
    case 'price-asc':
      sorted.sort((a, b) => a.price - b.price)
      break
    case 'price-desc':
      sorted.sort((a, b) => b.price - a.price)
      break
    default:
      sorted.sort((a, b) => new Date(b.created_at || b.createdAt || 0).getTime() - new Date(a.created_at || a.createdAt || 0).getTime())
  }

  return sorted
})

const totalResultLabel = computed(() => `${filteredProperties.value.length} bien${filteredProperties.value.length > 1 ? 's' : ''} disponible${filteredProperties.value.length > 1 ? 's' : ''}`)

const applyRouteFilters = () => {
  const city = typeof route.query.city === 'string' ? route.query.city : ''
  const budget = typeof route.query.budget === 'string' ? Number(route.query.budget) : NaN

  searchCity.value = city
  priceRange.value = [0, Number.isFinite(budget) && budget > 0 ? budget : priceLimit]
}

onMounted(async () => {
  applyRouteFilters()
  try {
    properties.value = await getProperties()
  } catch {
    properties.value = []
  }

  try {
    options.value = (await getList('/options')).map((option) => ({
      ...option,
      id: String(option.id),
    }))
  } catch {
    options.value = []
  }
})

watch(() => route.query, () => applyRouteFilters())

const toggleOption = (id: string) => {
  const index = selectedOptions.value.indexOf(id)
  if (index > -1) selectedOptions.value.splice(index, 1)
  else selectedOptions.value.push(id)
}

const clearFilters = () => {
  searchCity.value = ''
  priceRange.value = [0, priceLimit]
  selectedOptions.value = []
  sortBy.value = 'newest'
  router.replace({ query: {} })
}

const updateMinPrice = (e: Event) => {
  const value = Number((e.target as HTMLInputElement).value)
  priceRange.value = [value, priceRange.value[1]]
}

const updateMaxPrice = (e: Event) => {
  const value = Number((e.target as HTMLInputElement).value)
  priceRange.value = [priceRange.value[0], value]
}

const submitSearch = () => {
  router.replace({
    path: '/biens',
    query: {
      ...(searchCity.value ? { city: searchCity.value } : {}),
      ...(priceRange.value[1] < priceLimit ? { budget: String(priceRange.value[1]) } : {}),
    },
  })
}
</script>

<template>
  <div class="min-h-screen flex flex-col bg-slate-50">
    <PublicHeader />

    <main class="flex-1">
      <section class="relative overflow-hidden bg-slate-950 px-4 py-14 text-white sm:px-6 lg:px-8">
        <div class="absolute inset-0">
          <div class="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(14,165,233,0.24),transparent_28%),linear-gradient(120deg,rgba(3,7,18,0.94),rgba(15,23,42,0.88),rgba(30,41,59,0.92))]"></div>
        </div>
        <div class="relative mx-auto max-w-7xl">
          <div class="max-w-3xl">
            <p class="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/8 px-4 py-2 text-sm text-white/75 backdrop-blur">
              <Sparkles class="h-4 w-4 text-amber-300" />
              Locations de prestige à Abidjan & Assinie
            </p>
            <h1 class="text-4xl font-black leading-tight sm:text-5xl">
              Villas et appartements <span class="text-sky-500">de haut standing.</span>
            </h1>
            <p class="mt-5 max-w-2xl text-lg text-white/75">
              Explorez notre sélection exclusive et trouvez le bien idéal avec une recherche fluide et intuitive.
            </p>
          </div>
        </div>
      </section>

      <section class="mx-auto -mt-8 max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="bg-white rounded-[1.75rem] p-6 shadow-2xl border border-slate-100">
          <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between mb-6">
            <div>
              <h2 class="text-2xl font-black text-slate-950">Catalogue immobilier</h2>
              <p class="text-slate-500 text-sm mt-1">{{ totalResultLabel }}</p>
            </div>
            <div class="flex items-center gap-3 text-sm font-medium text-slate-500">
              <SlidersHorizontal class="h-4 w-4" />
              Filtres et tri dynamique
            </div>
          </div>

          <div class="grid gap-4 lg:grid-cols-[1fr_180px_auto]">
            <div class="relative">
              <Search class="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" />
              <input
                v-model="searchCity"
                type="text"
                placeholder="Ex: Cocody, Riviera, Assinie..."
                class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-12 py-4 text-slate-900 outline-none focus:ring-4 focus:ring-sky-500/10 focus:border-sky-500 transition-all"
                @keyup.enter="submitSearch"
              />
            </div>

            <select
              v-model="sortBy"
              class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4 text-slate-900 outline-none focus:ring-4 focus:ring-sky-500/10"
            >
              <option value="newest">Plus récents</option>
              <option value="price-asc">Prix croissant</option>
              <option value="price-desc">Prix décroissant</option>
            </select>

            <button
              class="inline-flex items-center justify-center gap-2 rounded-2xl px-6 py-4 font-bold transition-all"
              :class="showFilters ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'"
              @click="showFilters = !showFilters"
            >
              <SlidersHorizontal class="h-5 w-5" />
              Filtres
              <span v-if="selectedOptions.length > 0" class="rounded-full bg-sky-500 text-white px-2 py-0.5 text-[10px]">
                {{ selectedOptions.length }}
              </span>
            </button>
          </div>

          <div v-if="showFilters" class="mt-8 border-t border-slate-100 pt-8">
            <div class="grid gap-12 lg:grid-cols-2">
              <div>
                <label class="mb-4 block text-sm font-bold text-slate-900 uppercase">
                  Budget (FCFA) : {{ priceRange[0].toLocaleString() }} - {{ priceRange[1].toLocaleString() }}
                </label>
                <div class="flex gap-6">
                  <input :value="priceRange[0]" type="range" min="0" :max="priceLimit" step="5000" class="flex-1 accent-sky-500" @input="updateMinPrice" />
                  <input :value="priceRange[1]" type="range" min="0" :max="priceLimit" step="5000" class="flex-1 accent-sky-500" @input="updateMaxPrice" />
                </div>
              </div>

              <div>
                <label class="mb-4 block text-sm font-bold text-slate-900 uppercase">Équipements</label>
                <div class="flex flex-wrap gap-2">
                  <button
                    v-for="option in options"
                    :key="option.id"
                    :class="[
                      'rounded-xl px-4 py-2 text-sm font-bold transition-all',
                      selectedOptions.includes(option.id) ? 'bg-sky-500 text-white shadow-lg shadow-sky-200' : 'bg-slate-100 text-slate-600'
                    ]"
                    @click="toggleOption(option.id)"
                  >
                    {{ option.name }}
                  </button>
                </div>
              </div>
            </div>

            <div class="mt-8 flex justify-between items-center bg-slate-50 -mx-6 -mb-6 p-4 rounded-b-[1.75rem]">
              <button class="text-sm font-bold text-slate-400 hover:text-red-500 flex items-center gap-2" @click="clearFilters">
                <X class="h-4 w-4" /> Effacer
              </button>
              <button class="bg-sky-500 text-white px-8 py-3 rounded-xl font-bold shadow-lg shadow-sky-100 hover:bg-sky-600 transition-colors" @click="submitSearch">
                Appliquer
              </button>
            </div>
          </div>
        </div>
      </section>

      <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div v-if="filteredProperties.length > 0" class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          <PropertyCard
            v-for="property in filteredProperties"
            :key="property.id"
            :property="property"
          />
        </div>

        <div v-else class="text-center py-20 bg-white rounded-[2rem] border-2 border-dashed border-slate-200">
          <Search class="mx-auto h-12 w-12 text-slate-300 mb-4" />
          <h3 class="text-xl font-bold text-slate-950">Aucun bien ne correspond à vos critères</h3>
          <p class="text-slate-500 mt-2">Réduisez vos filtres ou élargissez votre zone de recherche.</p>
          <button class="mt-8 rounded-full bg-slate-950 px-8 py-3 text-sm font-bold text-white transition-transform hover:scale-105" @click="clearFilters">
            Réinitialiser tout
          </button>
        </div>
      </section>
    </main>

    <PublicFooter />
  </div>
</template>
